/*
EmailGuard Public API

Testing InvitesAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package emailguardsdk

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/EmailGuard/emailguard-go/emailguardsdk"
)

func Test_emailguardsdk_InvitesAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test InvitesAPIService ApiV1TeamMembersInvitesGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.InvitesAPI.ApiV1TeamMembersInvitesGet(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test InvitesAPIService ApiV1TeamMembersInvitesInviteIdDelete", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var inviteId string

		resp, httpRes, err := apiClient.InvitesAPI.ApiV1TeamMembersInvitesInviteIdDelete(context.Background(), inviteId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test InvitesAPIService ApiV1TeamMembersInvitesPost", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.InvitesAPI.ApiV1TeamMembersInvitesPost(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
