/*
EmailGuard Public API

Testing RulesAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package emailguardsdk

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/EmailGuard/emailguard-go/emailguardsdk"
)

func Test_emailguardsdk_RulesAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test RulesAPIService ApiV1TeamNotificationsRulesGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.RulesAPI.ApiV1TeamNotificationsRulesGet(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test RulesAPIService ApiV1TeamNotificationsRulesPost", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.RulesAPI.ApiV1TeamNotificationsRulesPost(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test RulesAPIService ApiV1TeamNotificationsRulesRuleIdDelete", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var ruleId string

		resp, httpRes, err := apiClient.RulesAPI.ApiV1TeamNotificationsRulesRuleIdDelete(context.Background(), ruleId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test RulesAPIService ApiV1TeamNotificationsRulesRuleIdPut", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var ruleId string

		resp, httpRes, err := apiClient.RulesAPI.ApiV1TeamNotificationsRulesRuleIdPut(context.Background(), ruleId).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
