/*
EmailGuard Public API

Testing EmailAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package emailguardsdk

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/EmailGuard/emailguard-go"
)

func Test_emailguardsdk_EmailAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test EmailAPIService ApiV1EmailsDetectGet", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.EmailAPI.ApiV1EmailsDetectGet(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
