// Code generated by scripts/clients/generate-go-facade.mjs; DO NOT EDIT.
package emailguardsdk

import (
	"context"

	"github.com/EmailGuard/emailguard-go/internal/openapi"
)

type BillingService struct {
	api *openapi.BillingAPIService
}

func newBillingService(transport *openapi.APIClient) *BillingService {
	return &BillingService{api: transport.BillingAPI}
}

type GetBillingUsageOptions struct {
	Range *string `json:"range,omitempty"`
	Start *string `json:"start,omitempty"`
	End *string `json:"end,omitempty"`
}

func (s *BillingService) GetBillingUsage(ctx context.Context, options *GetBillingUsageOptions) ([]BillingUsageItem, error) {
	request := s.api.GetBillingUsage(ctx)
	if options != nil && options.Range != nil {
		request = request.Range_(*options.Range)
	}
	if options != nil && options.Start != nil {
		request = request.Start(*options.Start)
	}
	if options != nil && options.End != nil {
		request = request.End(*options.End)
	}
	envelope, response, err := request.Execute()
	if err != nil {
		return nil, wrapHTTP(response, err)
	}
	if envelope == nil {
		return nil, newAPIError(0, "INVALID_RESPONSE", "API returned an empty response")
	}
	if err := checkEnvelope(envelope.Code, envelope.Message); err != nil {
		return nil, err
	}
	return envelope.Data, nil
}
