// Code generated by scripts/clients/generate-go-facade.mjs; DO NOT EDIT.
package emailguardsdk

import (
	"context"

	"github.com/EmailGuard/emailguard-go/internal/openapi"
)

type ChannelsService struct {
	api *openapi.ChannelsAPIService
}

func newChannelsService(transport *openapi.APIClient) *ChannelsService {
	return &ChannelsService{api: transport.ChannelsAPI}
}

func (s *ChannelsService) CreateNotificationChannel(ctx context.Context, input CreateNotificationChannelInput) (*NotificationChannelResponse, error) {
	request := s.api.CreateNotificationChannel(ctx).CreateNotificationChannelInput(input)
	envelope, response, err := request.Execute()
	if err != nil {
		return nil, wrapHTTP(response, err)
	}
	if envelope == nil {
		return nil, newAPIError(0, "INVALID_RESPONSE", "API returned an empty response")
	}
	if err := checkEnvelope(envelope.Code, envelope.Message); err != nil {
		return nil, err
	}
	if envelope.Data == nil {
		return nil, newAPIError(0, "INVALID_RESPONSE", "API response did not include data")
	}
	return envelope.Data, nil
}

func (s *ChannelsService) DeleteNotificationChannel(ctx context.Context, channelId string) error {
	request := s.api.DeleteNotificationChannel(ctx, channelId)
	envelope, response, err := request.Execute()
	if err != nil {
		return wrapHTTP(response, err)
	}
	if envelope == nil {
		return newAPIError(0, "INVALID_RESPONSE", "API returned an empty response")
	}
	if err := checkEnvelope(envelope.Code, envelope.Message); err != nil {
		return err
	}
	return nil
}

func (s *ChannelsService) ListNotificationChannels(ctx context.Context) ([]NotificationChannelResponse, error) {
	request := s.api.ListNotificationChannels(ctx)
	envelope, response, err := request.Execute()
	if err != nil {
		return nil, wrapHTTP(response, err)
	}
	if envelope == nil {
		return nil, newAPIError(0, "INVALID_RESPONSE", "API returned an empty response")
	}
	if err := checkEnvelope(envelope.Code, envelope.Message); err != nil {
		return nil, err
	}
	return envelope.Data, nil
}

func (s *ChannelsService) TestNotificationChannel(ctx context.Context, channelId string) error {
	request := s.api.TestNotificationChannel(ctx, channelId)
	envelope, response, err := request.Execute()
	if err != nil {
		return wrapHTTP(response, err)
	}
	if envelope == nil {
		return newAPIError(0, "INVALID_RESPONSE", "API returned an empty response")
	}
	if err := checkEnvelope(envelope.Code, envelope.Message); err != nil {
		return err
	}
	return nil
}

func (s *ChannelsService) UpdateNotificationChannel(ctx context.Context, channelId string, input UpdateNotificationChannelInput) (*NotificationChannelResponse, error) {
	request := s.api.UpdateNotificationChannel(ctx, channelId).UpdateNotificationChannelInput(input)
	envelope, response, err := request.Execute()
	if err != nil {
		return nil, wrapHTTP(response, err)
	}
	if envelope == nil {
		return nil, newAPIError(0, "INVALID_RESPONSE", "API returned an empty response")
	}
	if err := checkEnvelope(envelope.Code, envelope.Message); err != nil {
		return nil, err
	}
	if envelope.Data == nil {
		return nil, newAPIError(0, "INVALID_RESPONSE", "API response did not include data")
	}
	return envelope.Data, nil
}
