// Code generated by scripts/clients/generate-go-facade.mjs; DO NOT EDIT.
package emailguardsdk

import (
	"net/http"

	"github.com/EmailGuard/emailguard-go/internal/openapi"
)

type Option func(*openapi.Configuration)

func WithBaseURL(baseURL string) Option {
	return func(configuration *openapi.Configuration) {
		configuration.Servers[0].URL = baseURL
	}
}

func WithHTTPClient(client *http.Client) Option {
	return func(configuration *openapi.Configuration) {
		configuration.HTTPClient = client
	}
}

type Client struct {
	Invites *InvitesService
	Channels *ChannelsService
	Rules *RulesService
	Email *EmailService
	Billing *BillingService
	Teams *TeamsService
	Events *EventsService
	Members *MembersService
}

func New(apiKey string, options ...Option) *Client {
	configuration := openapi.NewConfiguration()
	configuration.AddDefaultHeader("Authorization", "Bearer "+apiKey)
	for _, option := range options {
		option(configuration)
	}
	transport := openapi.NewAPIClient(configuration)
	return &Client{
		Invites: newInvitesService(transport),
		Channels: newChannelsService(transport),
		Rules: newRulesService(transport),
		Email: newEmailService(transport),
		Billing: newBillingService(transport),
		Teams: newTeamsService(transport),
		Events: newEventsService(transport),
		Members: newMembersService(transport),
	}
}
