// Code generated by scripts/clients/generate-go-facade.mjs; DO NOT EDIT.
package emailguardsdk_test

import (
	"context"
	"errors"

	"net/http"
	"net/http/httptest"
	"testing"

	sdk "github.com/EmailGuard/emailguard-go"
)

func TestPublicOperations(t *testing.T) {
	t.Run("cancelPendingInvite", func(t *testing.T) {
		server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
			if r.Method != "DELETE" {
				t.Fatalf("method = %s", r.Method)
			}
			if r.URL.Path != "/api/v1/team/members/invites/example" {
				t.Fatalf("path = %s", r.URL.Path)
			}
			if r.Header.Get("Authorization") != "Bearer test-key" {
				t.Fatalf("authorization = %q", r.Header.Get("Authorization"))
			}
			w.Header().Set("Content-Type", "application/json")
			_, _ = w.Write([]byte("{\"code\":\"SUCCESS\",\"message\":\"ok\"}"))
		}))
		defer server.Close()
		client := sdk.New("test-key", sdk.WithBaseURL(server.URL))
		err := client.Invites.CancelPendingInvite(context.Background(), "example")
		if err != nil {
			t.Fatal(err)
		}
	})

	t.Run("createNotificationChannel", func(t *testing.T) {
		server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
			if r.Method != "POST" {
				t.Fatalf("method = %s", r.Method)
			}
			if r.URL.Path != "/api/v1/team/notifications/channels" {
				t.Fatalf("path = %s", r.URL.Path)
			}
			if r.Header.Get("Authorization") != "Bearer test-key" {
				t.Fatalf("authorization = %q", r.Header.Get("Authorization"))
			}
			w.Header().Set("Content-Type", "application/json")
			_, _ = w.Write([]byte("{\"code\":\"SUCCESS\",\"data\":{\"config\":{},\"created_at\":\"example\",\"id\":\"example\",\"is_verified\":false,\"name\":\"example\",\"type\":\"example\"},\"message\":\"ok\"}"))
		}))
		defer server.Close()
		client := sdk.New("test-key", sdk.WithBaseURL(server.URL))
		_, err := client.Channels.CreateNotificationChannel(context.Background(), sdk.CreateNotificationChannelInput{})
		if err != nil {
			t.Fatal(err)
		}
	})

	t.Run("createNotificationRule", func(t *testing.T) {
		server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
			if r.Method != "POST" {
				t.Fatalf("method = %s", r.Method)
			}
			if r.URL.Path != "/api/v1/team/notifications/rules" {
				t.Fatalf("path = %s", r.URL.Path)
			}
			if r.Header.Get("Authorization") != "Bearer test-key" {
				t.Fatalf("authorization = %q", r.Header.Get("Authorization"))
			}
			w.Header().Set("Content-Type", "application/json")
			_, _ = w.Write([]byte("{\"code\":\"SUCCESS\",\"data\":{\"id\":\"example\"},\"message\":\"ok\"}"))
		}))
		defer server.Close()
		client := sdk.New("test-key", sdk.WithBaseURL(server.URL))
		_, err := client.Rules.CreateNotificationRule(context.Background(), sdk.CreateNotificationRuleInput{})
		if err != nil {
			t.Fatal(err)
		}
	})

	t.Run("deleteNotificationChannel", func(t *testing.T) {
		server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
			if r.Method != "DELETE" {
				t.Fatalf("method = %s", r.Method)
			}
			if r.URL.Path != "/api/v1/team/notifications/channels/example" {
				t.Fatalf("path = %s", r.URL.Path)
			}
			if r.Header.Get("Authorization") != "Bearer test-key" {
				t.Fatalf("authorization = %q", r.Header.Get("Authorization"))
			}
			w.Header().Set("Content-Type", "application/json")
			_, _ = w.Write([]byte("{\"code\":\"SUCCESS\",\"message\":\"ok\"}"))
		}))
		defer server.Close()
		client := sdk.New("test-key", sdk.WithBaseURL(server.URL))
		err := client.Channels.DeleteNotificationChannel(context.Background(), "example")
		if err != nil {
			t.Fatal(err)
		}
	})

	t.Run("deleteNotificationRule", func(t *testing.T) {
		server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
			if r.Method != "DELETE" {
				t.Fatalf("method = %s", r.Method)
			}
			if r.URL.Path != "/api/v1/team/notifications/rules/example" {
				t.Fatalf("path = %s", r.URL.Path)
			}
			if r.Header.Get("Authorization") != "Bearer test-key" {
				t.Fatalf("authorization = %q", r.Header.Get("Authorization"))
			}
			w.Header().Set("Content-Type", "application/json")
			_, _ = w.Write([]byte("{\"code\":\"SUCCESS\",\"message\":\"ok\"}"))
		}))
		defer server.Close()
		client := sdk.New("test-key", sdk.WithBaseURL(server.URL))
		err := client.Rules.DeleteNotificationRule(context.Background(), "example")
		if err != nil {
			t.Fatal(err)
		}
	})

	t.Run("detectEmail", func(t *testing.T) {
		server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
			if r.Method != "GET" {
				t.Fatalf("method = %s", r.Method)
			}
			if r.URL.Path != "/api/v1/emails/detect" {
				t.Fatalf("path = %s", r.URL.Path)
			}
			if r.Header.Get("Authorization") != "Bearer test-key" {
				t.Fatalf("authorization = %q", r.Header.Get("Authorization"))
			}
			w.Header().Set("Content-Type", "application/json")
			_, _ = w.Write([]byte("{\"code\":\"SUCCESS\",\"data\":{\"confidence\":\"example\",\"detection_source\":\"example\",\"disposable\":false,\"disposable_provider\":\"example\",\"domain\":\"example\",\"email\":\"example\",\"evidence\":{\"cluster_provider\":\"example\",\"detection_layer\":\"example\",\"source_count\":0},\"infra_cluster_match\":false,\"matched_rules\":[],\"mx_present\":false,\"normalized\":\"example\",\"policy_action\":\"example\",\"public_domain\":false,\"relay_domain\":false,\"relay_provider\":\"example\",\"role_address\":false,\"subaddressing\":false,\"suggested_action\":\"example\",\"suggested_domain\":\"example\",\"suggested_email\":\"example\",\"syntax_validation\":false,\"wildcard_dns\":false},\"message\":\"ok\"}"))
		}))
		defer server.Close()
		client := sdk.New("test-key", sdk.WithBaseURL(server.URL))
		_, err := client.Email.DetectEmail(context.Background(), "example")
		if err != nil {
			t.Fatal(err)
		}
	})

	t.Run("getBillingUsage", func(t *testing.T) {
		server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
			if r.Method != "GET" {
				t.Fatalf("method = %s", r.Method)
			}
			if r.URL.Path != "/api/v1/team/billing/usage" {
				t.Fatalf("path = %s", r.URL.Path)
			}
			if r.Header.Get("Authorization") != "Bearer test-key" {
				t.Fatalf("authorization = %q", r.Header.Get("Authorization"))
			}
			w.Header().Set("Content-Type", "application/json")
			_, _ = w.Write([]byte("{\"code\":\"SUCCESS\",\"data\":[],\"message\":\"ok\"}"))
		}))
		defer server.Close()
		client := sdk.New("test-key", sdk.WithBaseURL(server.URL))
		_, err := client.Billing.GetBillingUsage(context.Background(), nil)
		if err != nil {
			t.Fatal(err)
		}
	})

	t.Run("getTeam", func(t *testing.T) {
		server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
			if r.Method != "GET" {
				t.Fatalf("method = %s", r.Method)
			}
			if r.URL.Path != "/api/v1/team" {
				t.Fatalf("path = %s", r.URL.Path)
			}
			if r.Header.Get("Authorization") != "Bearer test-key" {
				t.Fatalf("authorization = %q", r.Header.Get("Authorization"))
			}
			w.Header().Set("Content-Type", "application/json")
			_, _ = w.Write([]byte("{\"code\":\"SUCCESS\",\"data\":{\"email\":\"example\",\"emoji\":\"example\",\"id\":\"example\",\"name\":\"example\",\"type\":\"example\",\"url\":\"example\"},\"message\":\"ok\"}"))
		}))
		defer server.Close()
		client := sdk.New("test-key", sdk.WithBaseURL(server.URL))
		_, err := client.Teams.GetTeam(context.Background())
		if err != nil {
			t.Fatal(err)
		}
	})

	t.Run("inviteTeamMember", func(t *testing.T) {
		server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
			if r.Method != "POST" {
				t.Fatalf("method = %s", r.Method)
			}
			if r.URL.Path != "/api/v1/team/members/invites" {
				t.Fatalf("path = %s", r.URL.Path)
			}
			if r.Header.Get("Authorization") != "Bearer test-key" {
				t.Fatalf("authorization = %q", r.Header.Get("Authorization"))
			}
			w.Header().Set("Content-Type", "application/json")
			_, _ = w.Write([]byte("{\"code\":\"SUCCESS\",\"message\":\"ok\"}"))
		}))
		defer server.Close()
		client := sdk.New("test-key", sdk.WithBaseURL(server.URL))
		err := client.Invites.InviteTeamMember(context.Background(), sdk.InviteTeamMemberInput{})
		if err != nil {
			t.Fatal(err)
		}
	})

	t.Run("listNotificationChannels", func(t *testing.T) {
		server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
			if r.Method != "GET" {
				t.Fatalf("method = %s", r.Method)
			}
			if r.URL.Path != "/api/v1/team/notifications/channels" {
				t.Fatalf("path = %s", r.URL.Path)
			}
			if r.Header.Get("Authorization") != "Bearer test-key" {
				t.Fatalf("authorization = %q", r.Header.Get("Authorization"))
			}
			w.Header().Set("Content-Type", "application/json")
			_, _ = w.Write([]byte("{\"code\":\"SUCCESS\",\"data\":[],\"message\":\"ok\"}"))
		}))
		defer server.Close()
		client := sdk.New("test-key", sdk.WithBaseURL(server.URL))
		_, err := client.Channels.ListNotificationChannels(context.Background())
		if err != nil {
			t.Fatal(err)
		}
	})

	t.Run("listNotificationEvents", func(t *testing.T) {
		server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
			if r.Method != "GET" {
				t.Fatalf("method = %s", r.Method)
			}
			if r.URL.Path != "/api/v1/team/notifications/events" {
				t.Fatalf("path = %s", r.URL.Path)
			}
			if r.Header.Get("Authorization") != "Bearer test-key" {
				t.Fatalf("authorization = %q", r.Header.Get("Authorization"))
			}
			w.Header().Set("Content-Type", "application/json")
			_, _ = w.Write([]byte("{\"code\":\"SUCCESS\",\"data\":[],\"message\":\"ok\"}"))
		}))
		defer server.Close()
		client := sdk.New("test-key", sdk.WithBaseURL(server.URL))
		_, err := client.Events.ListNotificationEvents(context.Background())
		if err != nil {
			t.Fatal(err)
		}
	})

	t.Run("listNotificationRules", func(t *testing.T) {
		server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
			if r.Method != "GET" {
				t.Fatalf("method = %s", r.Method)
			}
			if r.URL.Path != "/api/v1/team/notifications/rules" {
				t.Fatalf("path = %s", r.URL.Path)
			}
			if r.Header.Get("Authorization") != "Bearer test-key" {
				t.Fatalf("authorization = %q", r.Header.Get("Authorization"))
			}
			w.Header().Set("Content-Type", "application/json")
			_, _ = w.Write([]byte("{\"code\":\"SUCCESS\",\"data\":[],\"message\":\"ok\"}"))
		}))
		defer server.Close()
		client := sdk.New("test-key", sdk.WithBaseURL(server.URL))
		_, err := client.Rules.ListNotificationRules(context.Background())
		if err != nil {
			t.Fatal(err)
		}
	})

	t.Run("listPendingTeamInvites", func(t *testing.T) {
		server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
			if r.Method != "GET" {
				t.Fatalf("method = %s", r.Method)
			}
			if r.URL.Path != "/api/v1/team/members/invites" {
				t.Fatalf("path = %s", r.URL.Path)
			}
			if r.Header.Get("Authorization") != "Bearer test-key" {
				t.Fatalf("authorization = %q", r.Header.Get("Authorization"))
			}
			w.Header().Set("Content-Type", "application/json")
			_, _ = w.Write([]byte("{\"code\":\"SUCCESS\",\"data\":[],\"message\":\"ok\"}"))
		}))
		defer server.Close()
		client := sdk.New("test-key", sdk.WithBaseURL(server.URL))
		_, err := client.Invites.ListPendingTeamInvites(context.Background())
		if err != nil {
			t.Fatal(err)
		}
	})

	t.Run("listTeamMembers", func(t *testing.T) {
		server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
			if r.Method != "GET" {
				t.Fatalf("method = %s", r.Method)
			}
			if r.URL.Path != "/api/v1/team/members" {
				t.Fatalf("path = %s", r.URL.Path)
			}
			if r.Header.Get("Authorization") != "Bearer test-key" {
				t.Fatalf("authorization = %q", r.Header.Get("Authorization"))
			}
			w.Header().Set("Content-Type", "application/json")
			_, _ = w.Write([]byte("{\"code\":\"SUCCESS\",\"data\":[],\"message\":\"ok\"}"))
		}))
		defer server.Close()
		client := sdk.New("test-key", sdk.WithBaseURL(server.URL))
		_, err := client.Members.ListTeamMembers(context.Background())
		if err != nil {
			t.Fatal(err)
		}
	})

	t.Run("removeTeamMember", func(t *testing.T) {
		server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
			if r.Method != "DELETE" {
				t.Fatalf("method = %s", r.Method)
			}
			if r.URL.Path != "/api/v1/team/members/example" {
				t.Fatalf("path = %s", r.URL.Path)
			}
			if r.Header.Get("Authorization") != "Bearer test-key" {
				t.Fatalf("authorization = %q", r.Header.Get("Authorization"))
			}
			w.Header().Set("Content-Type", "application/json")
			_, _ = w.Write([]byte("{\"code\":\"SUCCESS\",\"message\":\"ok\"}"))
		}))
		defer server.Close()
		client := sdk.New("test-key", sdk.WithBaseURL(server.URL))
		err := client.Members.RemoveTeamMember(context.Background(), "example")
		if err != nil {
			t.Fatal(err)
		}
	})

	t.Run("testNotificationChannel", func(t *testing.T) {
		server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
			if r.Method != "POST" {
				t.Fatalf("method = %s", r.Method)
			}
			if r.URL.Path != "/api/v1/team/notifications/channels/example/test" {
				t.Fatalf("path = %s", r.URL.Path)
			}
			if r.Header.Get("Authorization") != "Bearer test-key" {
				t.Fatalf("authorization = %q", r.Header.Get("Authorization"))
			}
			w.Header().Set("Content-Type", "application/json")
			_, _ = w.Write([]byte("{\"code\":\"SUCCESS\",\"message\":\"ok\"}"))
		}))
		defer server.Close()
		client := sdk.New("test-key", sdk.WithBaseURL(server.URL))
		err := client.Channels.TestNotificationChannel(context.Background(), "example")
		if err != nil {
			t.Fatal(err)
		}
	})

	t.Run("updateNotificationChannel", func(t *testing.T) {
		server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
			if r.Method != "PUT" {
				t.Fatalf("method = %s", r.Method)
			}
			if r.URL.Path != "/api/v1/team/notifications/channels/example" {
				t.Fatalf("path = %s", r.URL.Path)
			}
			if r.Header.Get("Authorization") != "Bearer test-key" {
				t.Fatalf("authorization = %q", r.Header.Get("Authorization"))
			}
			w.Header().Set("Content-Type", "application/json")
			_, _ = w.Write([]byte("{\"code\":\"SUCCESS\",\"data\":{\"config\":{},\"created_at\":\"example\",\"id\":\"example\",\"is_verified\":false,\"name\":\"example\",\"type\":\"example\"},\"message\":\"ok\"}"))
		}))
		defer server.Close()
		client := sdk.New("test-key", sdk.WithBaseURL(server.URL))
		_, err := client.Channels.UpdateNotificationChannel(context.Background(), "example", sdk.UpdateNotificationChannelInput{})
		if err != nil {
			t.Fatal(err)
		}
	})

	t.Run("updateNotificationRule", func(t *testing.T) {
		server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
			if r.Method != "PUT" {
				t.Fatalf("method = %s", r.Method)
			}
			if r.URL.Path != "/api/v1/team/notifications/rules/example" {
				t.Fatalf("path = %s", r.URL.Path)
			}
			if r.Header.Get("Authorization") != "Bearer test-key" {
				t.Fatalf("authorization = %q", r.Header.Get("Authorization"))
			}
			w.Header().Set("Content-Type", "application/json")
			_, _ = w.Write([]byte("{\"code\":\"SUCCESS\",\"message\":\"ok\"}"))
		}))
		defer server.Close()
		client := sdk.New("test-key", sdk.WithBaseURL(server.URL))
		err := client.Rules.UpdateNotificationRule(context.Background(), "example", sdk.UpdateNotificationRuleInput{})
		if err != nil {
			t.Fatal(err)
		}
	})

	t.Run("updateTeam", func(t *testing.T) {
		server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
			if r.Method != "PATCH" {
				t.Fatalf("method = %s", r.Method)
			}
			if r.URL.Path != "/api/v1/team" {
				t.Fatalf("path = %s", r.URL.Path)
			}
			if r.Header.Get("Authorization") != "Bearer test-key" {
				t.Fatalf("authorization = %q", r.Header.Get("Authorization"))
			}
			w.Header().Set("Content-Type", "application/json")
			_, _ = w.Write([]byte("{\"code\":\"SUCCESS\",\"data\":{\"email\":\"example\",\"emoji\":\"example\",\"id\":\"example\",\"name\":\"example\",\"type\":\"example\",\"url\":\"example\"},\"message\":\"ok\"}"))
		}))
		defer server.Close()
		client := sdk.New("test-key", sdk.WithBaseURL(server.URL))
		_, err := client.Teams.UpdateTeam(context.Background(), sdk.UpdateTeamInput{})
		if err != nil {
			t.Fatal(err)
		}
	})

	t.Run("updateTeamMember", func(t *testing.T) {
		server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
			if r.Method != "PATCH" {
				t.Fatalf("method = %s", r.Method)
			}
			if r.URL.Path != "/api/v1/team/members/example" {
				t.Fatalf("path = %s", r.URL.Path)
			}
			if r.Header.Get("Authorization") != "Bearer test-key" {
				t.Fatalf("authorization = %q", r.Header.Get("Authorization"))
			}
			w.Header().Set("Content-Type", "application/json")
			_, _ = w.Write([]byte("{\"code\":\"SUCCESS\",\"message\":\"ok\"}"))
		}))
		defer server.Close()
		client := sdk.New("test-key", sdk.WithBaseURL(server.URL))
		err := client.Members.UpdateTeamMember(context.Background(), "example", sdk.PublicUpdateTeamMemberInput{})
		if err != nil {
			t.Fatal(err)
		}
	})

	t.Run("non_2xx", func(t *testing.T) {
		server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, _ *http.Request) {
			w.Header().Set("Content-Type", "application/json")
			w.WriteHeader(400)
			_, _ = w.Write([]byte("{\"code\":\"INVALID_BODY\",\"message\":\"Invalid request\"}"))
		}))
		defer server.Close()
		client := sdk.New("test-key", sdk.WithBaseURL(server.URL))
		_, err := client.Channels.CreateNotificationChannel(context.Background(), sdk.CreateNotificationChannelInput{})
		if err == nil {
			t.Fatal("expected API error")
		}
		var apiError *sdk.APIError
		if !errors.As(err, &apiError) {
			t.Fatalf("error type = %T", err)
		}
	})

	t.Run("unsuccessful_envelope", func(t *testing.T) {
		server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, _ *http.Request) {
			w.Header().Set("Content-Type", "application/json")
			w.WriteHeader(200)
			_, _ = w.Write([]byte("{\"code\":\"RATE_LIMITED\",\"message\":\"Try later\"}"))
		}))
		defer server.Close()
		client := sdk.New("test-key", sdk.WithBaseURL(server.URL))
		_, err := client.Channels.CreateNotificationChannel(context.Background(), sdk.CreateNotificationChannelInput{})
		if err == nil {
			t.Fatal("expected API error")
		}
		var apiError *sdk.APIError
		if !errors.As(err, &apiError) {
			t.Fatalf("error type = %T", err)
		}
	})

	t.Run("malformed_json", func(t *testing.T) {
		server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, _ *http.Request) {
			w.Header().Set("Content-Type", "application/json")
			w.WriteHeader(200)
			_, _ = w.Write([]byte("not json"))
		}))
		defer server.Close()
		client := sdk.New("test-key", sdk.WithBaseURL(server.URL))
		_, err := client.Channels.CreateNotificationChannel(context.Background(), sdk.CreateNotificationChannelInput{})
		if err == nil {
			t.Fatal("expected API error")
		}
		var apiError *sdk.APIError
		if !errors.As(err, &apiError) {
			t.Fatalf("error type = %T", err)
		}
	})

	t.Run("missing_data", func(t *testing.T) {
		server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, _ *http.Request) {
			w.Header().Set("Content-Type", "application/json")
			w.WriteHeader(200)
			_, _ = w.Write([]byte("{\"code\":\"SUCCESS\"}"))
		}))
		defer server.Close()
		client := sdk.New("test-key", sdk.WithBaseURL(server.URL))
		_, err := client.Channels.CreateNotificationChannel(context.Background(), sdk.CreateNotificationChannelInput{})
		if err == nil {
			t.Fatal("expected API error")
		}
		var apiError *sdk.APIError
		if !errors.As(err, &apiError) {
			t.Fatalf("error type = %T", err)
		}
	})
}
