// Code generated by scripts/clients/generate-go-facade.mjs; DO NOT EDIT.
package emailguardsdk

import (
	"context"

	"github.com/EmailGuard/emailguard-go/internal/openapi"
)

type EmailService struct {
	api *openapi.EmailAPIService
}

func newEmailService(transport *openapi.APIClient) *EmailService {
	return &EmailService{api: transport.EmailAPI}
}

func (s *EmailService) DetectEmail(ctx context.Context, email string) (*EmailDetectData, error) {
	request := s.api.DetectEmail(ctx).Email(email)
	envelope, response, err := request.Execute()
	if err != nil {
		return nil, wrapHTTP(response, err)
	}
	if envelope == nil {
		return nil, newAPIError(0, "INVALID_RESPONSE", "API returned an empty response")
	}
	if err := checkEnvelope(envelope.Code, envelope.Message); err != nil {
		return nil, err
	}
	if envelope.Data == nil {
		return nil, newAPIError(0, "INVALID_RESPONSE", "API response did not include data")
	}
	return envelope.Data, nil
}
