// Code generated by scripts/clients/generate-go-facade.mjs; DO NOT EDIT.
package emailguardsdk

import (
	"bytes"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
)

// APIError is returned for HTTP failures, unsuccessful API envelopes, and
// invalid success responses.
type APIError struct {
	Status  int
	Code    string
	Message string
}

func (e *APIError) Error() string {
	if e.Code == "" {
		return e.Message
	}
	return fmt.Sprintf("%s: %s", e.Code, e.Message)
}

func newAPIError(status int, code, message string) error {
	return &APIError{Status: status, Code: code, Message: message}
}

func checkEnvelope(code string, message *string) error {
	if code == "SUCCESS" {
		return nil
	}
	detail := "API returned an unsuccessful response"
	if message != nil && *message != "" {
		detail = *message
	}
	return newAPIError(http.StatusOK, code, detail)
}

func wrapHTTP(response *http.Response, cause error) error {
	if response == nil {
		return newAPIError(0, "", cause.Error())
	}
	var envelope struct {
		Code string `json:"code"`
		Message string `json:"message"`
	}
	if response.Body != nil {
		body, _ := io.ReadAll(response.Body)
		response.Body = io.NopCloser(bytes.NewReader(body))
		_ = json.Unmarshal(body, &envelope)
	}
	message := envelope.Message
	if message == "" {
		message = cause.Error()
	}
	return newAPIError(response.StatusCode, envelope.Code, message)
}
