// Code generated by scripts/clients/generate-go-facade.mjs; DO NOT EDIT.
package emailguardsdk

import (
	"context"

	"github.com/EmailGuard/emailguard-go/internal/openapi"
)

type EventsService struct {
	api *openapi.EventsAPIService
}

func newEventsService(transport *openapi.APIClient) *EventsService {
	return &EventsService{api: transport.EventsAPI}
}

func (s *EventsService) ListNotificationEvents(ctx context.Context) ([]string, error) {
	request := s.api.ListNotificationEvents(ctx)
	envelope, response, err := request.Execute()
	if err != nil {
		return nil, wrapHTTP(response, err)
	}
	if envelope == nil {
		return nil, newAPIError(0, "INVALID_RESPONSE", "API returned an empty response")
	}
	if err := checkEnvelope(envelope.Code, envelope.Message); err != nil {
		return nil, err
	}
	return envelope.Data, nil
}
