// Code generated by scripts/clients/generate-go-facade.mjs; DO NOT EDIT.
package emailguardsdk

import (
	"context"

	"github.com/EmailGuard/emailguard-go/internal/openapi"
)

type InvitesService struct {
	api *openapi.InvitesAPIService
}

func newInvitesService(transport *openapi.APIClient) *InvitesService {
	return &InvitesService{api: transport.InvitesAPI}
}

func (s *InvitesService) CancelPendingInvite(ctx context.Context, inviteId string) error {
	request := s.api.CancelPendingInvite(ctx, inviteId)
	envelope, response, err := request.Execute()
	if err != nil {
		return wrapHTTP(response, err)
	}
	if envelope == nil {
		return newAPIError(0, "INVALID_RESPONSE", "API returned an empty response")
	}
	if err := checkEnvelope(envelope.Code, envelope.Message); err != nil {
		return err
	}
	return nil
}

func (s *InvitesService) InviteTeamMember(ctx context.Context, input InviteTeamMemberInput) error {
	request := s.api.InviteTeamMember(ctx).InviteTeamMemberInput(input)
	envelope, response, err := request.Execute()
	if err != nil {
		return wrapHTTP(response, err)
	}
	if envelope == nil {
		return newAPIError(0, "INVALID_RESPONSE", "API returned an empty response")
	}
	if err := checkEnvelope(envelope.Code, envelope.Message); err != nil {
		return err
	}
	return nil
}

func (s *InvitesService) ListPendingTeamInvites(ctx context.Context) ([]PublicTeamInviteResponse, error) {
	request := s.api.ListPendingTeamInvites(ctx)
	envelope, response, err := request.Execute()
	if err != nil {
		return nil, wrapHTTP(response, err)
	}
	if envelope == nil {
		return nil, newAPIError(0, "INVALID_RESPONSE", "API returned an empty response")
	}
	if err := checkEnvelope(envelope.Code, envelope.Message); err != nil {
		return nil, err
	}
	return envelope.Data, nil
}
