// Code generated by scripts/clients/generate-go-facade.mjs; DO NOT EDIT.
package emailguardsdk

import (
	"context"

	"github.com/EmailGuard/emailguard-go/internal/openapi"
)

type MembersService struct {
	api *openapi.MembersAPIService
}

func newMembersService(transport *openapi.APIClient) *MembersService {
	return &MembersService{api: transport.MembersAPI}
}

func (s *MembersService) ListTeamMembers(ctx context.Context) ([]PublicTeamMemberResponse, error) {
	request := s.api.ListTeamMembers(ctx)
	envelope, response, err := request.Execute()
	if err != nil {
		return nil, wrapHTTP(response, err)
	}
	if envelope == nil {
		return nil, newAPIError(0, "INVALID_RESPONSE", "API returned an empty response")
	}
	if err := checkEnvelope(envelope.Code, envelope.Message); err != nil {
		return nil, err
	}
	return envelope.Data, nil
}

func (s *MembersService) RemoveTeamMember(ctx context.Context, userId string) error {
	request := s.api.RemoveTeamMember(ctx, userId)
	envelope, response, err := request.Execute()
	if err != nil {
		return wrapHTTP(response, err)
	}
	if envelope == nil {
		return newAPIError(0, "INVALID_RESPONSE", "API returned an empty response")
	}
	if err := checkEnvelope(envelope.Code, envelope.Message); err != nil {
		return err
	}
	return nil
}

func (s *MembersService) UpdateTeamMember(ctx context.Context, userId string, input PublicUpdateTeamMemberInput) error {
	request := s.api.UpdateTeamMember(ctx, userId).PublicUpdateTeamMemberInput(input)
	envelope, response, err := request.Execute()
	if err != nil {
		return wrapHTTP(response, err)
	}
	if envelope == nil {
		return newAPIError(0, "INVALID_RESPONSE", "API returned an empty response")
	}
	if err := checkEnvelope(envelope.Code, envelope.Message); err != nil {
		return err
	}
	return nil
}
