/*
EmailGuard Public API

Team-scoped REST API at /api/v1. Authenticate with `Authorization: Bearer egsk_live_...` or `X-API-Key`. Forks may register custom routes under /api/v1/tools/_* (requires `tools:read` / `tools:write` scopes). Async tool jobs return a `job_id` — poll `GET .../{jobId}/results` until complete. See /docs/api-reference.

API version: 1.0
Contact: dev@emailguard.co
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package emailguardsdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CreateNotificationChannelInput type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateNotificationChannelInput{}

// CreateNotificationChannelInput struct for CreateNotificationChannelInput
type CreateNotificationChannelInput struct {
	// Type-specific configuration (email address, webhook URL, headers, and so on).
	Config map[string]interface{} `json:"config,omitempty"`
	// Display name shown in team notification settings.
	Name string `json:"name"`
	// Channel type (for example email or webhook).
	Type string `json:"type"`
}

type _CreateNotificationChannelInput CreateNotificationChannelInput

// NewCreateNotificationChannelInput instantiates a new CreateNotificationChannelInput object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateNotificationChannelInput(name string, type_ string) *CreateNotificationChannelInput {
	this := CreateNotificationChannelInput{}
	this.Name = name
	this.Type = type_
	return &this
}

// NewCreateNotificationChannelInputWithDefaults instantiates a new CreateNotificationChannelInput object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateNotificationChannelInputWithDefaults() *CreateNotificationChannelInput {
	this := CreateNotificationChannelInput{}
	return &this
}

// GetConfig returns the Config field value if set, zero value otherwise.
func (o *CreateNotificationChannelInput) GetConfig() map[string]interface{} {
	if o == nil || IsNil(o.Config) {
		var ret map[string]interface{}
		return ret
	}
	return o.Config
}

// GetConfigOk returns a tuple with the Config field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateNotificationChannelInput) GetConfigOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Config) {
		return map[string]interface{}{}, false
	}
	return o.Config, true
}

// HasConfig returns a boolean if a field has been set.
func (o *CreateNotificationChannelInput) HasConfig() bool {
	if o != nil && !IsNil(o.Config) {
		return true
	}

	return false
}

// SetConfig gets a reference to the given map[string]interface{} and assigns it to the Config field.
func (o *CreateNotificationChannelInput) SetConfig(v map[string]interface{}) {
	o.Config = v
}

// GetName returns the Name field value
func (o *CreateNotificationChannelInput) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *CreateNotificationChannelInput) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *CreateNotificationChannelInput) SetName(v string) {
	o.Name = v
}

// GetType returns the Type field value
func (o *CreateNotificationChannelInput) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *CreateNotificationChannelInput) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *CreateNotificationChannelInput) SetType(v string) {
	o.Type = v
}

func (o CreateNotificationChannelInput) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateNotificationChannelInput) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Config) {
		toSerialize["config"] = o.Config
	}
	toSerialize["name"] = o.Name
	toSerialize["type"] = o.Type
	return toSerialize, nil
}

func (o *CreateNotificationChannelInput) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
		"type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateNotificationChannelInput := _CreateNotificationChannelInput{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateNotificationChannelInput)

	if err != nil {
		return err
	}

	*o = CreateNotificationChannelInput(varCreateNotificationChannelInput)

	return err
}

type NullableCreateNotificationChannelInput struct {
	value *CreateNotificationChannelInput
	isSet bool
}

func (v NullableCreateNotificationChannelInput) Get() *CreateNotificationChannelInput {
	return v.value
}

func (v *NullableCreateNotificationChannelInput) Set(val *CreateNotificationChannelInput) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateNotificationChannelInput) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateNotificationChannelInput) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateNotificationChannelInput(val *CreateNotificationChannelInput) *NullableCreateNotificationChannelInput {
	return &NullableCreateNotificationChannelInput{value: val, isSet: true}
}

func (v NullableCreateNotificationChannelInput) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateNotificationChannelInput) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


