/*
EmailGuard Public API

Team-scoped REST API at /api/v1. Authenticate with `Authorization: Bearer egsk_live_...` or `X-API-Key`. Forks may register custom routes under /api/v1/tools/_* (requires `tools:read` / `tools:write` scopes). Async tool jobs return a `job_id` — poll `GET .../{jobId}/results` until complete. See /docs/api-reference.

API version: 1.0
Contact: dev@emailguard.co
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package emailguardsdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the UpdateTeamInput type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateTeamInput{}

// UpdateTeamInput struct for UpdateTeamInput
type UpdateTeamInput struct {
	// Contact email address for the team workspace.
	Email *string `json:"email,omitempty"`
	// Single grapheme emoji shown as the team avatar in the product UI.
	Emoji *string `json:"emoji,omitempty"`
	// Human-readable team name.
	Name string `json:"name"`
	// Public website URL for the team.
	Url *string `json:"url,omitempty"`
}

type _UpdateTeamInput UpdateTeamInput

// NewUpdateTeamInput instantiates a new UpdateTeamInput object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateTeamInput(name string) *UpdateTeamInput {
	this := UpdateTeamInput{}
	this.Name = name
	return &this
}

// NewUpdateTeamInputWithDefaults instantiates a new UpdateTeamInput object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateTeamInputWithDefaults() *UpdateTeamInput {
	this := UpdateTeamInput{}
	return &this
}

// GetEmail returns the Email field value if set, zero value otherwise.
func (o *UpdateTeamInput) GetEmail() string {
	if o == nil || IsNil(o.Email) {
		var ret string
		return ret
	}
	return *o.Email
}

// GetEmailOk returns a tuple with the Email field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateTeamInput) GetEmailOk() (*string, bool) {
	if o == nil || IsNil(o.Email) {
		return nil, false
	}
	return o.Email, true
}

// HasEmail returns a boolean if a field has been set.
func (o *UpdateTeamInput) HasEmail() bool {
	if o != nil && !IsNil(o.Email) {
		return true
	}

	return false
}

// SetEmail gets a reference to the given string and assigns it to the Email field.
func (o *UpdateTeamInput) SetEmail(v string) {
	o.Email = &v
}

// GetEmoji returns the Emoji field value if set, zero value otherwise.
func (o *UpdateTeamInput) GetEmoji() string {
	if o == nil || IsNil(o.Emoji) {
		var ret string
		return ret
	}
	return *o.Emoji
}

// GetEmojiOk returns a tuple with the Emoji field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateTeamInput) GetEmojiOk() (*string, bool) {
	if o == nil || IsNil(o.Emoji) {
		return nil, false
	}
	return o.Emoji, true
}

// HasEmoji returns a boolean if a field has been set.
func (o *UpdateTeamInput) HasEmoji() bool {
	if o != nil && !IsNil(o.Emoji) {
		return true
	}

	return false
}

// SetEmoji gets a reference to the given string and assigns it to the Emoji field.
func (o *UpdateTeamInput) SetEmoji(v string) {
	o.Emoji = &v
}

// GetName returns the Name field value
func (o *UpdateTeamInput) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *UpdateTeamInput) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *UpdateTeamInput) SetName(v string) {
	o.Name = v
}

// GetUrl returns the Url field value if set, zero value otherwise.
func (o *UpdateTeamInput) GetUrl() string {
	if o == nil || IsNil(o.Url) {
		var ret string
		return ret
	}
	return *o.Url
}

// GetUrlOk returns a tuple with the Url field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateTeamInput) GetUrlOk() (*string, bool) {
	if o == nil || IsNil(o.Url) {
		return nil, false
	}
	return o.Url, true
}

// HasUrl returns a boolean if a field has been set.
func (o *UpdateTeamInput) HasUrl() bool {
	if o != nil && !IsNil(o.Url) {
		return true
	}

	return false
}

// SetUrl gets a reference to the given string and assigns it to the Url field.
func (o *UpdateTeamInput) SetUrl(v string) {
	o.Url = &v
}

func (o UpdateTeamInput) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateTeamInput) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Email) {
		toSerialize["email"] = o.Email
	}
	if !IsNil(o.Emoji) {
		toSerialize["emoji"] = o.Emoji
	}
	toSerialize["name"] = o.Name
	if !IsNil(o.Url) {
		toSerialize["url"] = o.Url
	}
	return toSerialize, nil
}

func (o *UpdateTeamInput) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUpdateTeamInput := _UpdateTeamInput{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUpdateTeamInput)

	if err != nil {
		return err
	}

	*o = UpdateTeamInput(varUpdateTeamInput)

	return err
}

type NullableUpdateTeamInput struct {
	value *UpdateTeamInput
	isSet bool
}

func (v NullableUpdateTeamInput) Get() *UpdateTeamInput {
	return v.value
}

func (v *NullableUpdateTeamInput) Set(val *UpdateTeamInput) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateTeamInput) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateTeamInput) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateTeamInput(val *UpdateTeamInput) *NullableUpdateTeamInput {
	return &NullableUpdateTeamInput{value: val, isSet: true}
}

func (v NullableUpdateTeamInput) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateTeamInput) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


