/*
EmailGuard Public API

Team-scoped REST API at /api/v1. Authenticate with `Authorization: Bearer egsk_live_...` or `X-API-Key`. Forks may register custom routes under /api/v1/tools/_* (requires `tools:read` / `tools:write` scopes). Async tool jobs return a `job_id` — poll `GET .../{jobId}/results` until complete. See /docs/api-reference.

API version: 1.0
Contact: dev@emailguard.co
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package emailguardsdk

import (
	"encoding/json"
)

// checks if the UpdateNotificationRuleInput type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateNotificationRuleInput{}

// UpdateNotificationRuleInput struct for UpdateNotificationRuleInput
type UpdateNotificationRuleInput struct {
	// Replaces all channel targets when provided.
	Channels []NotificationRuleChannelInput `json:"channels,omitempty"`
	// Updated conditions. Omit to leave unchanged.
	Conditions map[string]interface{} `json:"conditions,omitempty"`
	// Updated description. Omit to leave unchanged.
	Description *string `json:"description,omitempty"`
	// Updated event types. Omit to leave unchanged.
	EventTypes []string `json:"event_types,omitempty"`
	// Enable or disable delivery for this rule.
	IsEnabled *bool `json:"is_enabled,omitempty"`
	// Updated display name. Omit to leave unchanged.
	Name *string `json:"name,omitempty"`
}

// NewUpdateNotificationRuleInput instantiates a new UpdateNotificationRuleInput object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateNotificationRuleInput() *UpdateNotificationRuleInput {
	this := UpdateNotificationRuleInput{}
	return &this
}

// NewUpdateNotificationRuleInputWithDefaults instantiates a new UpdateNotificationRuleInput object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateNotificationRuleInputWithDefaults() *UpdateNotificationRuleInput {
	this := UpdateNotificationRuleInput{}
	return &this
}

// GetChannels returns the Channels field value if set, zero value otherwise.
func (o *UpdateNotificationRuleInput) GetChannels() []NotificationRuleChannelInput {
	if o == nil || IsNil(o.Channels) {
		var ret []NotificationRuleChannelInput
		return ret
	}
	return o.Channels
}

// GetChannelsOk returns a tuple with the Channels field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateNotificationRuleInput) GetChannelsOk() ([]NotificationRuleChannelInput, bool) {
	if o == nil || IsNil(o.Channels) {
		return nil, false
	}
	return o.Channels, true
}

// HasChannels returns a boolean if a field has been set.
func (o *UpdateNotificationRuleInput) HasChannels() bool {
	if o != nil && !IsNil(o.Channels) {
		return true
	}

	return false
}

// SetChannels gets a reference to the given []NotificationRuleChannelInput and assigns it to the Channels field.
func (o *UpdateNotificationRuleInput) SetChannels(v []NotificationRuleChannelInput) {
	o.Channels = v
}

// GetConditions returns the Conditions field value if set, zero value otherwise.
func (o *UpdateNotificationRuleInput) GetConditions() map[string]interface{} {
	if o == nil || IsNil(o.Conditions) {
		var ret map[string]interface{}
		return ret
	}
	return o.Conditions
}

// GetConditionsOk returns a tuple with the Conditions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateNotificationRuleInput) GetConditionsOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Conditions) {
		return map[string]interface{}{}, false
	}
	return o.Conditions, true
}

// HasConditions returns a boolean if a field has been set.
func (o *UpdateNotificationRuleInput) HasConditions() bool {
	if o != nil && !IsNil(o.Conditions) {
		return true
	}

	return false
}

// SetConditions gets a reference to the given map[string]interface{} and assigns it to the Conditions field.
func (o *UpdateNotificationRuleInput) SetConditions(v map[string]interface{}) {
	o.Conditions = v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *UpdateNotificationRuleInput) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateNotificationRuleInput) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *UpdateNotificationRuleInput) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *UpdateNotificationRuleInput) SetDescription(v string) {
	o.Description = &v
}

// GetEventTypes returns the EventTypes field value if set, zero value otherwise.
func (o *UpdateNotificationRuleInput) GetEventTypes() []string {
	if o == nil || IsNil(o.EventTypes) {
		var ret []string
		return ret
	}
	return o.EventTypes
}

// GetEventTypesOk returns a tuple with the EventTypes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateNotificationRuleInput) GetEventTypesOk() ([]string, bool) {
	if o == nil || IsNil(o.EventTypes) {
		return nil, false
	}
	return o.EventTypes, true
}

// HasEventTypes returns a boolean if a field has been set.
func (o *UpdateNotificationRuleInput) HasEventTypes() bool {
	if o != nil && !IsNil(o.EventTypes) {
		return true
	}

	return false
}

// SetEventTypes gets a reference to the given []string and assigns it to the EventTypes field.
func (o *UpdateNotificationRuleInput) SetEventTypes(v []string) {
	o.EventTypes = v
}

// GetIsEnabled returns the IsEnabled field value if set, zero value otherwise.
func (o *UpdateNotificationRuleInput) GetIsEnabled() bool {
	if o == nil || IsNil(o.IsEnabled) {
		var ret bool
		return ret
	}
	return *o.IsEnabled
}

// GetIsEnabledOk returns a tuple with the IsEnabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateNotificationRuleInput) GetIsEnabledOk() (*bool, bool) {
	if o == nil || IsNil(o.IsEnabled) {
		return nil, false
	}
	return o.IsEnabled, true
}

// HasIsEnabled returns a boolean if a field has been set.
func (o *UpdateNotificationRuleInput) HasIsEnabled() bool {
	if o != nil && !IsNil(o.IsEnabled) {
		return true
	}

	return false
}

// SetIsEnabled gets a reference to the given bool and assigns it to the IsEnabled field.
func (o *UpdateNotificationRuleInput) SetIsEnabled(v bool) {
	o.IsEnabled = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *UpdateNotificationRuleInput) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateNotificationRuleInput) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *UpdateNotificationRuleInput) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *UpdateNotificationRuleInput) SetName(v string) {
	o.Name = &v
}

func (o UpdateNotificationRuleInput) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateNotificationRuleInput) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Channels) {
		toSerialize["channels"] = o.Channels
	}
	if !IsNil(o.Conditions) {
		toSerialize["conditions"] = o.Conditions
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.EventTypes) {
		toSerialize["event_types"] = o.EventTypes
	}
	if !IsNil(o.IsEnabled) {
		toSerialize["is_enabled"] = o.IsEnabled
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	return toSerialize, nil
}

type NullableUpdateNotificationRuleInput struct {
	value *UpdateNotificationRuleInput
	isSet bool
}

func (v NullableUpdateNotificationRuleInput) Get() *UpdateNotificationRuleInput {
	return v.value
}

func (v *NullableUpdateNotificationRuleInput) Set(val *UpdateNotificationRuleInput) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateNotificationRuleInput) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateNotificationRuleInput) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateNotificationRuleInput(val *UpdateNotificationRuleInput) *NullableUpdateNotificationRuleInput {
	return &NullableUpdateNotificationRuleInput{value: val, isSet: true}
}

func (v NullableUpdateNotificationRuleInput) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateNotificationRuleInput) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


