/*
EmailGuard Public API

Team-scoped REST API at /api/v1. Authenticate with `Authorization: Bearer egsk_live_...` or `X-API-Key`. Forks may register custom routes under /api/v1/tools/_* (requires `tools:read` / `tools:write` scopes). Async tool jobs return a `job_id` — poll `GET .../{jobId}/results` until complete. See /docs/api-reference.

API version: 1.0
Contact: dev@emailguard.co
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package emailguardsdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the CreateNotificationRuleInput type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateNotificationRuleInput{}

// CreateNotificationRuleInput struct for CreateNotificationRuleInput
type CreateNotificationRuleInput struct {
	// One or more channel targets to notify when matching events occur.
	Channels []NotificationRuleChannelInput `json:"channels"`
	// Optional rule conditions (e.g. usage_threshold for USAGE_API_THRESHOLD).
	Conditions map[string]interface{} `json:"conditions,omitempty"`
	// Optional longer description of what the rule does.
	Description *string `json:"description,omitempty"`
	// Event type identifiers this rule listens for (at least one required).
	EventTypes []string `json:"event_types"`
	// When false, the rule is stored but does not deliver events.
	IsEnabled *bool `json:"is_enabled,omitempty"`
	// Display name for the rule.
	Name string `json:"name"`
}

type _CreateNotificationRuleInput CreateNotificationRuleInput

// NewCreateNotificationRuleInput instantiates a new CreateNotificationRuleInput object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateNotificationRuleInput(channels []NotificationRuleChannelInput, eventTypes []string, name string) *CreateNotificationRuleInput {
	this := CreateNotificationRuleInput{}
	this.Channels = channels
	this.EventTypes = eventTypes
	this.Name = name
	return &this
}

// NewCreateNotificationRuleInputWithDefaults instantiates a new CreateNotificationRuleInput object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateNotificationRuleInputWithDefaults() *CreateNotificationRuleInput {
	this := CreateNotificationRuleInput{}
	return &this
}

// GetChannels returns the Channels field value
func (o *CreateNotificationRuleInput) GetChannels() []NotificationRuleChannelInput {
	if o == nil {
		var ret []NotificationRuleChannelInput
		return ret
	}

	return o.Channels
}

// GetChannelsOk returns a tuple with the Channels field value
// and a boolean to check if the value has been set.
func (o *CreateNotificationRuleInput) GetChannelsOk() ([]NotificationRuleChannelInput, bool) {
	if o == nil {
		return nil, false
	}
	return o.Channels, true
}

// SetChannels sets field value
func (o *CreateNotificationRuleInput) SetChannels(v []NotificationRuleChannelInput) {
	o.Channels = v
}

// GetConditions returns the Conditions field value if set, zero value otherwise.
func (o *CreateNotificationRuleInput) GetConditions() map[string]interface{} {
	if o == nil || IsNil(o.Conditions) {
		var ret map[string]interface{}
		return ret
	}
	return o.Conditions
}

// GetConditionsOk returns a tuple with the Conditions field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateNotificationRuleInput) GetConditionsOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Conditions) {
		return map[string]interface{}{}, false
	}
	return o.Conditions, true
}

// HasConditions returns a boolean if a field has been set.
func (o *CreateNotificationRuleInput) HasConditions() bool {
	if o != nil && !IsNil(o.Conditions) {
		return true
	}

	return false
}

// SetConditions gets a reference to the given map[string]interface{} and assigns it to the Conditions field.
func (o *CreateNotificationRuleInput) SetConditions(v map[string]interface{}) {
	o.Conditions = v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *CreateNotificationRuleInput) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateNotificationRuleInput) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *CreateNotificationRuleInput) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *CreateNotificationRuleInput) SetDescription(v string) {
	o.Description = &v
}

// GetEventTypes returns the EventTypes field value
func (o *CreateNotificationRuleInput) GetEventTypes() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.EventTypes
}

// GetEventTypesOk returns a tuple with the EventTypes field value
// and a boolean to check if the value has been set.
func (o *CreateNotificationRuleInput) GetEventTypesOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.EventTypes, true
}

// SetEventTypes sets field value
func (o *CreateNotificationRuleInput) SetEventTypes(v []string) {
	o.EventTypes = v
}

// GetIsEnabled returns the IsEnabled field value if set, zero value otherwise.
func (o *CreateNotificationRuleInput) GetIsEnabled() bool {
	if o == nil || IsNil(o.IsEnabled) {
		var ret bool
		return ret
	}
	return *o.IsEnabled
}

// GetIsEnabledOk returns a tuple with the IsEnabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateNotificationRuleInput) GetIsEnabledOk() (*bool, bool) {
	if o == nil || IsNil(o.IsEnabled) {
		return nil, false
	}
	return o.IsEnabled, true
}

// HasIsEnabled returns a boolean if a field has been set.
func (o *CreateNotificationRuleInput) HasIsEnabled() bool {
	if o != nil && !IsNil(o.IsEnabled) {
		return true
	}

	return false
}

// SetIsEnabled gets a reference to the given bool and assigns it to the IsEnabled field.
func (o *CreateNotificationRuleInput) SetIsEnabled(v bool) {
	o.IsEnabled = &v
}

// GetName returns the Name field value
func (o *CreateNotificationRuleInput) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *CreateNotificationRuleInput) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *CreateNotificationRuleInput) SetName(v string) {
	o.Name = v
}

func (o CreateNotificationRuleInput) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateNotificationRuleInput) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["channels"] = o.Channels
	if !IsNil(o.Conditions) {
		toSerialize["conditions"] = o.Conditions
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	toSerialize["event_types"] = o.EventTypes
	if !IsNil(o.IsEnabled) {
		toSerialize["is_enabled"] = o.IsEnabled
	}
	toSerialize["name"] = o.Name
	return toSerialize, nil
}

func (o *CreateNotificationRuleInput) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"channels",
		"event_types",
		"name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varCreateNotificationRuleInput := _CreateNotificationRuleInput{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varCreateNotificationRuleInput)

	if err != nil {
		return err
	}

	*o = CreateNotificationRuleInput(varCreateNotificationRuleInput)

	return err
}

type NullableCreateNotificationRuleInput struct {
	value *CreateNotificationRuleInput
	isSet bool
}

func (v NullableCreateNotificationRuleInput) Get() *CreateNotificationRuleInput {
	return v.value
}

func (v *NullableCreateNotificationRuleInput) Set(val *CreateNotificationRuleInput) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateNotificationRuleInput) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateNotificationRuleInput) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateNotificationRuleInput(val *CreateNotificationRuleInput) *NullableCreateNotificationRuleInput {
	return &NullableCreateNotificationRuleInput{value: val, isSet: true}
}

func (v NullableCreateNotificationRuleInput) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateNotificationRuleInput) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


