/*
EmailGuard Public API

Team-scoped REST API at /api/v1. Authenticate with `Authorization: Bearer egsk_live_...` or `X-API-Key`. Forks may register custom routes under /api/v1/tools/_* (requires `tools:read` / `tools:write` scopes). Async tool jobs return a `job_id` — poll `GET .../{jobId}/results` until complete. See /docs/api-reference.

API version: 1.0
Contact: dev@emailguard.co
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package emailguardsdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the InviteTeamMemberInput type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &InviteTeamMemberInput{}

// InviteTeamMemberInput struct for InviteTeamMemberInput
type InviteTeamMemberInput struct {
	// Email address that will receive the invite.
	Email string `json:"email"`
	// Team role to assign when the invite is accepted (for example Owner, Admin, Member). See [Team roles and permissions](/docs/knowledge-base/team-roles-and-permissions).
	Role string `json:"role"`
}

type _InviteTeamMemberInput InviteTeamMemberInput

// NewInviteTeamMemberInput instantiates a new InviteTeamMemberInput object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewInviteTeamMemberInput(email string, role string) *InviteTeamMemberInput {
	this := InviteTeamMemberInput{}
	this.Email = email
	this.Role = role
	return &this
}

// NewInviteTeamMemberInputWithDefaults instantiates a new InviteTeamMemberInput object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewInviteTeamMemberInputWithDefaults() *InviteTeamMemberInput {
	this := InviteTeamMemberInput{}
	return &this
}

// GetEmail returns the Email field value
func (o *InviteTeamMemberInput) GetEmail() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Email
}

// GetEmailOk returns a tuple with the Email field value
// and a boolean to check if the value has been set.
func (o *InviteTeamMemberInput) GetEmailOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Email, true
}

// SetEmail sets field value
func (o *InviteTeamMemberInput) SetEmail(v string) {
	o.Email = v
}

// GetRole returns the Role field value
func (o *InviteTeamMemberInput) GetRole() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Role
}

// GetRoleOk returns a tuple with the Role field value
// and a boolean to check if the value has been set.
func (o *InviteTeamMemberInput) GetRoleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Role, true
}

// SetRole sets field value
func (o *InviteTeamMemberInput) SetRole(v string) {
	o.Role = v
}

func (o InviteTeamMemberInput) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o InviteTeamMemberInput) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["email"] = o.Email
	toSerialize["role"] = o.Role
	return toSerialize, nil
}

func (o *InviteTeamMemberInput) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"email",
		"role",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varInviteTeamMemberInput := _InviteTeamMemberInput{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varInviteTeamMemberInput)

	if err != nil {
		return err
	}

	*o = InviteTeamMemberInput(varInviteTeamMemberInput)

	return err
}

type NullableInviteTeamMemberInput struct {
	value *InviteTeamMemberInput
	isSet bool
}

func (v NullableInviteTeamMemberInput) Get() *InviteTeamMemberInput {
	return v.value
}

func (v *NullableInviteTeamMemberInput) Set(val *InviteTeamMemberInput) {
	v.value = val
	v.isSet = true
}

func (v NullableInviteTeamMemberInput) IsSet() bool {
	return v.isSet
}

func (v *NullableInviteTeamMemberInput) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableInviteTeamMemberInput(val *InviteTeamMemberInput) *NullableInviteTeamMemberInput {
	return &NullableInviteTeamMemberInput{value: val, isSet: true}
}

func (v NullableInviteTeamMemberInput) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableInviteTeamMemberInput) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


