/*
EmailGuard Public API

Team-scoped REST API at /api/v1. Authenticate with `Authorization: Bearer egsk_live_...` or `X-API-Key`. Forks may register custom routes under /api/v1/tools/_* (requires `tools:read` / `tools:write` scopes). Async tool jobs return a `job_id` — poll `GET .../{jobId}/results` until complete. See /docs/api-reference.

API version: 1.0
Contact: dev@emailguard.co
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package emailguardsdk

import (
	"encoding/json"
)

// checks if the IdDataStruct type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &IdDataStruct{}

// IdDataStruct struct for IdDataStruct
type IdDataStruct struct {
	// UUID of the created or referenced record.
	Id *string `json:"id,omitempty"`
}

// NewIdDataStruct instantiates a new IdDataStruct object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewIdDataStruct() *IdDataStruct {
	this := IdDataStruct{}
	return &this
}

// NewIdDataStructWithDefaults instantiates a new IdDataStruct object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewIdDataStructWithDefaults() *IdDataStruct {
	this := IdDataStruct{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *IdDataStruct) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IdDataStruct) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *IdDataStruct) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *IdDataStruct) SetId(v string) {
	o.Id = &v
}

func (o IdDataStruct) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o IdDataStruct) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	return toSerialize, nil
}

type NullableIdDataStruct struct {
	value *IdDataStruct
	isSet bool
}

func (v NullableIdDataStruct) Get() *IdDataStruct {
	return v.value
}

func (v *NullableIdDataStruct) Set(val *IdDataStruct) {
	v.value = val
	v.isSet = true
}

func (v NullableIdDataStruct) IsSet() bool {
	return v.isSet
}

func (v *NullableIdDataStruct) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIdDataStruct(val *IdDataStruct) *NullableIdDataStruct {
	return &NullableIdDataStruct{value: val, isSet: true}
}

func (v NullableIdDataStruct) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIdDataStruct) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


