/*
EmailGuard Public API

Team-scoped REST API at /api/v1. Authenticate with `Authorization: Bearer egsk_live_...` or `X-API-Key`. Forks may register custom routes under /api/v1/tools/_* (requires `tools:read` / `tools:write` scopes). Async tool jobs return a `job_id` — poll `GET .../{jobId}/results` until complete. See /docs/api-reference.

API version: 1.0
Contact: dev@emailguard.co
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package emailguardsdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the PublicTeamMemberResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PublicTeamMemberResponse{}

// PublicTeamMemberResponse struct for PublicTeamMemberResponse
type PublicTeamMemberResponse struct {
	// When the member joined the team (RFC3339).
	CreatedAt string `json:"created_at"`
	// Member login email.
	Email string `json:"email"`
	// User profile emoji.
	Emoji *string `json:"emoji,omitempty"`
	// Member given name.
	FirstName string `json:"first_name"`
	// Team membership record ID.
	Id string `json:"id"`
	// Member family name.
	LastName string `json:"last_name"`
	// Internal notes stored on the membership.
	Notes *string `json:"notes,omitempty"`
	// Team role (for example Owner, Admin, Member).
	Role string `json:"role"`
	// User account ID for this member.
	UserId string `json:"user_id"`
}

type _PublicTeamMemberResponse PublicTeamMemberResponse

// NewPublicTeamMemberResponse instantiates a new PublicTeamMemberResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPublicTeamMemberResponse(createdAt string, email string, firstName string, id string, lastName string, role string, userId string) *PublicTeamMemberResponse {
	this := PublicTeamMemberResponse{}
	this.CreatedAt = createdAt
	this.Email = email
	this.FirstName = firstName
	this.Id = id
	this.LastName = lastName
	this.Role = role
	this.UserId = userId
	return &this
}

// NewPublicTeamMemberResponseWithDefaults instantiates a new PublicTeamMemberResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPublicTeamMemberResponseWithDefaults() *PublicTeamMemberResponse {
	this := PublicTeamMemberResponse{}
	return &this
}

// GetCreatedAt returns the CreatedAt field value
func (o *PublicTeamMemberResponse) GetCreatedAt() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value
// and a boolean to check if the value has been set.
func (o *PublicTeamMemberResponse) GetCreatedAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CreatedAt, true
}

// SetCreatedAt sets field value
func (o *PublicTeamMemberResponse) SetCreatedAt(v string) {
	o.CreatedAt = v
}

// GetEmail returns the Email field value
func (o *PublicTeamMemberResponse) GetEmail() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Email
}

// GetEmailOk returns a tuple with the Email field value
// and a boolean to check if the value has been set.
func (o *PublicTeamMemberResponse) GetEmailOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Email, true
}

// SetEmail sets field value
func (o *PublicTeamMemberResponse) SetEmail(v string) {
	o.Email = v
}

// GetEmoji returns the Emoji field value if set, zero value otherwise.
func (o *PublicTeamMemberResponse) GetEmoji() string {
	if o == nil || IsNil(o.Emoji) {
		var ret string
		return ret
	}
	return *o.Emoji
}

// GetEmojiOk returns a tuple with the Emoji field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PublicTeamMemberResponse) GetEmojiOk() (*string, bool) {
	if o == nil || IsNil(o.Emoji) {
		return nil, false
	}
	return o.Emoji, true
}

// HasEmoji returns a boolean if a field has been set.
func (o *PublicTeamMemberResponse) HasEmoji() bool {
	if o != nil && !IsNil(o.Emoji) {
		return true
	}

	return false
}

// SetEmoji gets a reference to the given string and assigns it to the Emoji field.
func (o *PublicTeamMemberResponse) SetEmoji(v string) {
	o.Emoji = &v
}

// GetFirstName returns the FirstName field value
func (o *PublicTeamMemberResponse) GetFirstName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.FirstName
}

// GetFirstNameOk returns a tuple with the FirstName field value
// and a boolean to check if the value has been set.
func (o *PublicTeamMemberResponse) GetFirstNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FirstName, true
}

// SetFirstName sets field value
func (o *PublicTeamMemberResponse) SetFirstName(v string) {
	o.FirstName = v
}

// GetId returns the Id field value
func (o *PublicTeamMemberResponse) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *PublicTeamMemberResponse) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *PublicTeamMemberResponse) SetId(v string) {
	o.Id = v
}

// GetLastName returns the LastName field value
func (o *PublicTeamMemberResponse) GetLastName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.LastName
}

// GetLastNameOk returns a tuple with the LastName field value
// and a boolean to check if the value has been set.
func (o *PublicTeamMemberResponse) GetLastNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.LastName, true
}

// SetLastName sets field value
func (o *PublicTeamMemberResponse) SetLastName(v string) {
	o.LastName = v
}

// GetNotes returns the Notes field value if set, zero value otherwise.
func (o *PublicTeamMemberResponse) GetNotes() string {
	if o == nil || IsNil(o.Notes) {
		var ret string
		return ret
	}
	return *o.Notes
}

// GetNotesOk returns a tuple with the Notes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PublicTeamMemberResponse) GetNotesOk() (*string, bool) {
	if o == nil || IsNil(o.Notes) {
		return nil, false
	}
	return o.Notes, true
}

// HasNotes returns a boolean if a field has been set.
func (o *PublicTeamMemberResponse) HasNotes() bool {
	if o != nil && !IsNil(o.Notes) {
		return true
	}

	return false
}

// SetNotes gets a reference to the given string and assigns it to the Notes field.
func (o *PublicTeamMemberResponse) SetNotes(v string) {
	o.Notes = &v
}

// GetRole returns the Role field value
func (o *PublicTeamMemberResponse) GetRole() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Role
}

// GetRoleOk returns a tuple with the Role field value
// and a boolean to check if the value has been set.
func (o *PublicTeamMemberResponse) GetRoleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Role, true
}

// SetRole sets field value
func (o *PublicTeamMemberResponse) SetRole(v string) {
	o.Role = v
}

// GetUserId returns the UserId field value
func (o *PublicTeamMemberResponse) GetUserId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.UserId
}

// GetUserIdOk returns a tuple with the UserId field value
// and a boolean to check if the value has been set.
func (o *PublicTeamMemberResponse) GetUserIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UserId, true
}

// SetUserId sets field value
func (o *PublicTeamMemberResponse) SetUserId(v string) {
	o.UserId = v
}

func (o PublicTeamMemberResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PublicTeamMemberResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["created_at"] = o.CreatedAt
	toSerialize["email"] = o.Email
	if !IsNil(o.Emoji) {
		toSerialize["emoji"] = o.Emoji
	}
	toSerialize["first_name"] = o.FirstName
	toSerialize["id"] = o.Id
	toSerialize["last_name"] = o.LastName
	if !IsNil(o.Notes) {
		toSerialize["notes"] = o.Notes
	}
	toSerialize["role"] = o.Role
	toSerialize["user_id"] = o.UserId
	return toSerialize, nil
}

func (o *PublicTeamMemberResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"created_at",
		"email",
		"first_name",
		"id",
		"last_name",
		"role",
		"user_id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPublicTeamMemberResponse := _PublicTeamMemberResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPublicTeamMemberResponse)

	if err != nil {
		return err
	}

	*o = PublicTeamMemberResponse(varPublicTeamMemberResponse)

	return err
}

type NullablePublicTeamMemberResponse struct {
	value *PublicTeamMemberResponse
	isSet bool
}

func (v NullablePublicTeamMemberResponse) Get() *PublicTeamMemberResponse {
	return v.value
}

func (v *NullablePublicTeamMemberResponse) Set(val *PublicTeamMemberResponse) {
	v.value = val
	v.isSet = true
}

func (v NullablePublicTeamMemberResponse) IsSet() bool {
	return v.isSet
}

func (v *NullablePublicTeamMemberResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePublicTeamMemberResponse(val *PublicTeamMemberResponse) *NullablePublicTeamMemberResponse {
	return &NullablePublicTeamMemberResponse{value: val, isSet: true}
}

func (v NullablePublicTeamMemberResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePublicTeamMemberResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


