/*
EmailGuard Public API

Team-scoped REST API at /api/v1. Authenticate with `Authorization: Bearer egsk_live_...` or `X-API-Key`. Forks may register custom routes under /api/v1/tools/_* (requires `tools:read` / `tools:write` scopes). Async tool jobs return a `job_id` — poll `GET .../{jobId}/results` until complete. See /docs/api-reference.

API version: 1.0
Contact: dev@emailguard.co
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package emailguardsdk

import (
	"encoding/json"
)

// checks if the NotificationRuleChannelInput type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &NotificationRuleChannelInput{}

// NotificationRuleChannelInput struct for NotificationRuleChannelInput
type NotificationRuleChannelInput struct {
	// UUID of a team notification channel. Use this or predefined, not both.
	ChannelId *string `json:"channel_id,omitempty"`
	// Built-in channel identifier when not using a custom channel.
	Predefined *string `json:"predefined,omitempty"`
	// Restrict delivery to a specific team member's user ID.
	TargetUserId *string `json:"target_user_id,omitempty"`
}

// NewNotificationRuleChannelInput instantiates a new NotificationRuleChannelInput object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNotificationRuleChannelInput() *NotificationRuleChannelInput {
	this := NotificationRuleChannelInput{}
	return &this
}

// NewNotificationRuleChannelInputWithDefaults instantiates a new NotificationRuleChannelInput object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNotificationRuleChannelInputWithDefaults() *NotificationRuleChannelInput {
	this := NotificationRuleChannelInput{}
	return &this
}

// GetChannelId returns the ChannelId field value if set, zero value otherwise.
func (o *NotificationRuleChannelInput) GetChannelId() string {
	if o == nil || IsNil(o.ChannelId) {
		var ret string
		return ret
	}
	return *o.ChannelId
}

// GetChannelIdOk returns a tuple with the ChannelId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NotificationRuleChannelInput) GetChannelIdOk() (*string, bool) {
	if o == nil || IsNil(o.ChannelId) {
		return nil, false
	}
	return o.ChannelId, true
}

// HasChannelId returns a boolean if a field has been set.
func (o *NotificationRuleChannelInput) HasChannelId() bool {
	if o != nil && !IsNil(o.ChannelId) {
		return true
	}

	return false
}

// SetChannelId gets a reference to the given string and assigns it to the ChannelId field.
func (o *NotificationRuleChannelInput) SetChannelId(v string) {
	o.ChannelId = &v
}

// GetPredefined returns the Predefined field value if set, zero value otherwise.
func (o *NotificationRuleChannelInput) GetPredefined() string {
	if o == nil || IsNil(o.Predefined) {
		var ret string
		return ret
	}
	return *o.Predefined
}

// GetPredefinedOk returns a tuple with the Predefined field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NotificationRuleChannelInput) GetPredefinedOk() (*string, bool) {
	if o == nil || IsNil(o.Predefined) {
		return nil, false
	}
	return o.Predefined, true
}

// HasPredefined returns a boolean if a field has been set.
func (o *NotificationRuleChannelInput) HasPredefined() bool {
	if o != nil && !IsNil(o.Predefined) {
		return true
	}

	return false
}

// SetPredefined gets a reference to the given string and assigns it to the Predefined field.
func (o *NotificationRuleChannelInput) SetPredefined(v string) {
	o.Predefined = &v
}

// GetTargetUserId returns the TargetUserId field value if set, zero value otherwise.
func (o *NotificationRuleChannelInput) GetTargetUserId() string {
	if o == nil || IsNil(o.TargetUserId) {
		var ret string
		return ret
	}
	return *o.TargetUserId
}

// GetTargetUserIdOk returns a tuple with the TargetUserId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NotificationRuleChannelInput) GetTargetUserIdOk() (*string, bool) {
	if o == nil || IsNil(o.TargetUserId) {
		return nil, false
	}
	return o.TargetUserId, true
}

// HasTargetUserId returns a boolean if a field has been set.
func (o *NotificationRuleChannelInput) HasTargetUserId() bool {
	if o != nil && !IsNil(o.TargetUserId) {
		return true
	}

	return false
}

// SetTargetUserId gets a reference to the given string and assigns it to the TargetUserId field.
func (o *NotificationRuleChannelInput) SetTargetUserId(v string) {
	o.TargetUserId = &v
}

func (o NotificationRuleChannelInput) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o NotificationRuleChannelInput) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ChannelId) {
		toSerialize["channel_id"] = o.ChannelId
	}
	if !IsNil(o.Predefined) {
		toSerialize["predefined"] = o.Predefined
	}
	if !IsNil(o.TargetUserId) {
		toSerialize["target_user_id"] = o.TargetUserId
	}
	return toSerialize, nil
}

type NullableNotificationRuleChannelInput struct {
	value *NotificationRuleChannelInput
	isSet bool
}

func (v NullableNotificationRuleChannelInput) Get() *NotificationRuleChannelInput {
	return v.value
}

func (v *NullableNotificationRuleChannelInput) Set(val *NotificationRuleChannelInput) {
	v.value = val
	v.isSet = true
}

func (v NullableNotificationRuleChannelInput) IsSet() bool {
	return v.isSet
}

func (v *NullableNotificationRuleChannelInput) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNotificationRuleChannelInput(val *NotificationRuleChannelInput) *NullableNotificationRuleChannelInput {
	return &NullableNotificationRuleChannelInput{value: val, isSet: true}
}

func (v NullableNotificationRuleChannelInput) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNotificationRuleChannelInput) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


