/*
EmailGuard Public API

Team-scoped REST API at /api/v1. Authenticate with `Authorization: Bearer egsk_live_...` or `X-API-Key`. Forks may register custom routes under /api/v1/tools/_* (requires `tools:read` / `tools:write` scopes). Async tool jobs return a `job_id` — poll `GET .../{jobId}/results` until complete. See /docs/api-reference.

API version: 1.0
Contact: dev@emailguard.co
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package emailguardsdk

import (
	"encoding/json"
)

// checks if the EmailDetectData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EmailDetectData{}

// EmailDetectData struct for EmailDetectData
type EmailDetectData struct {
	DetectionSource *string `json:"detection_source,omitempty"`
	Disposable *bool `json:"disposable,omitempty"`
	DisposableProvider *string `json:"disposable_provider,omitempty"`
	Domain *string `json:"domain,omitempty"`
	Email *string `json:"email,omitempty"`
	Normalized *string `json:"normalized,omitempty"`
	PublicDomain *bool `json:"public_domain,omitempty"`
	RelayDomain *bool `json:"relay_domain,omitempty"`
	RelayProvider *string `json:"relay_provider,omitempty"`
	RoleAddress *bool `json:"role_address,omitempty"`
	Subaddressing *bool `json:"subaddressing,omitempty"`
	// Corrected domain candidate when a domain or TLD typo rule matches.
	SuggestedDomain *string `json:"suggested_domain,omitempty"`
	// Corrected email candidate when a domain or TLD typo rule matches.
	SuggestedEmail *string `json:"suggested_email,omitempty"`
	SyntaxValidation *bool `json:"syntax_validation,omitempty"`
}

// NewEmailDetectData instantiates a new EmailDetectData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEmailDetectData() *EmailDetectData {
	this := EmailDetectData{}
	return &this
}

// NewEmailDetectDataWithDefaults instantiates a new EmailDetectData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEmailDetectDataWithDefaults() *EmailDetectData {
	this := EmailDetectData{}
	return &this
}

// GetDetectionSource returns the DetectionSource field value if set, zero value otherwise.
func (o *EmailDetectData) GetDetectionSource() string {
	if o == nil || IsNil(o.DetectionSource) {
		var ret string
		return ret
	}
	return *o.DetectionSource
}

// GetDetectionSourceOk returns a tuple with the DetectionSource field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EmailDetectData) GetDetectionSourceOk() (*string, bool) {
	if o == nil || IsNil(o.DetectionSource) {
		return nil, false
	}
	return o.DetectionSource, true
}

// HasDetectionSource returns a boolean if a field has been set.
func (o *EmailDetectData) HasDetectionSource() bool {
	if o != nil && !IsNil(o.DetectionSource) {
		return true
	}

	return false
}

// SetDetectionSource gets a reference to the given string and assigns it to the DetectionSource field.
func (o *EmailDetectData) SetDetectionSource(v string) {
	o.DetectionSource = &v
}

// GetDisposable returns the Disposable field value if set, zero value otherwise.
func (o *EmailDetectData) GetDisposable() bool {
	if o == nil || IsNil(o.Disposable) {
		var ret bool
		return ret
	}
	return *o.Disposable
}

// GetDisposableOk returns a tuple with the Disposable field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EmailDetectData) GetDisposableOk() (*bool, bool) {
	if o == nil || IsNil(o.Disposable) {
		return nil, false
	}
	return o.Disposable, true
}

// HasDisposable returns a boolean if a field has been set.
func (o *EmailDetectData) HasDisposable() bool {
	if o != nil && !IsNil(o.Disposable) {
		return true
	}

	return false
}

// SetDisposable gets a reference to the given bool and assigns it to the Disposable field.
func (o *EmailDetectData) SetDisposable(v bool) {
	o.Disposable = &v
}

// GetDisposableProvider returns the DisposableProvider field value if set, zero value otherwise.
func (o *EmailDetectData) GetDisposableProvider() string {
	if o == nil || IsNil(o.DisposableProvider) {
		var ret string
		return ret
	}
	return *o.DisposableProvider
}

// GetDisposableProviderOk returns a tuple with the DisposableProvider field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EmailDetectData) GetDisposableProviderOk() (*string, bool) {
	if o == nil || IsNil(o.DisposableProvider) {
		return nil, false
	}
	return o.DisposableProvider, true
}

// HasDisposableProvider returns a boolean if a field has been set.
func (o *EmailDetectData) HasDisposableProvider() bool {
	if o != nil && !IsNil(o.DisposableProvider) {
		return true
	}

	return false
}

// SetDisposableProvider gets a reference to the given string and assigns it to the DisposableProvider field.
func (o *EmailDetectData) SetDisposableProvider(v string) {
	o.DisposableProvider = &v
}

// GetDomain returns the Domain field value if set, zero value otherwise.
func (o *EmailDetectData) GetDomain() string {
	if o == nil || IsNil(o.Domain) {
		var ret string
		return ret
	}
	return *o.Domain
}

// GetDomainOk returns a tuple with the Domain field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EmailDetectData) GetDomainOk() (*string, bool) {
	if o == nil || IsNil(o.Domain) {
		return nil, false
	}
	return o.Domain, true
}

// HasDomain returns a boolean if a field has been set.
func (o *EmailDetectData) HasDomain() bool {
	if o != nil && !IsNil(o.Domain) {
		return true
	}

	return false
}

// SetDomain gets a reference to the given string and assigns it to the Domain field.
func (o *EmailDetectData) SetDomain(v string) {
	o.Domain = &v
}

// GetEmail returns the Email field value if set, zero value otherwise.
func (o *EmailDetectData) GetEmail() string {
	if o == nil || IsNil(o.Email) {
		var ret string
		return ret
	}
	return *o.Email
}

// GetEmailOk returns a tuple with the Email field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EmailDetectData) GetEmailOk() (*string, bool) {
	if o == nil || IsNil(o.Email) {
		return nil, false
	}
	return o.Email, true
}

// HasEmail returns a boolean if a field has been set.
func (o *EmailDetectData) HasEmail() bool {
	if o != nil && !IsNil(o.Email) {
		return true
	}

	return false
}

// SetEmail gets a reference to the given string and assigns it to the Email field.
func (o *EmailDetectData) SetEmail(v string) {
	o.Email = &v
}

// GetNormalized returns the Normalized field value if set, zero value otherwise.
func (o *EmailDetectData) GetNormalized() string {
	if o == nil || IsNil(o.Normalized) {
		var ret string
		return ret
	}
	return *o.Normalized
}

// GetNormalizedOk returns a tuple with the Normalized field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EmailDetectData) GetNormalizedOk() (*string, bool) {
	if o == nil || IsNil(o.Normalized) {
		return nil, false
	}
	return o.Normalized, true
}

// HasNormalized returns a boolean if a field has been set.
func (o *EmailDetectData) HasNormalized() bool {
	if o != nil && !IsNil(o.Normalized) {
		return true
	}

	return false
}

// SetNormalized gets a reference to the given string and assigns it to the Normalized field.
func (o *EmailDetectData) SetNormalized(v string) {
	o.Normalized = &v
}

// GetPublicDomain returns the PublicDomain field value if set, zero value otherwise.
func (o *EmailDetectData) GetPublicDomain() bool {
	if o == nil || IsNil(o.PublicDomain) {
		var ret bool
		return ret
	}
	return *o.PublicDomain
}

// GetPublicDomainOk returns a tuple with the PublicDomain field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EmailDetectData) GetPublicDomainOk() (*bool, bool) {
	if o == nil || IsNil(o.PublicDomain) {
		return nil, false
	}
	return o.PublicDomain, true
}

// HasPublicDomain returns a boolean if a field has been set.
func (o *EmailDetectData) HasPublicDomain() bool {
	if o != nil && !IsNil(o.PublicDomain) {
		return true
	}

	return false
}

// SetPublicDomain gets a reference to the given bool and assigns it to the PublicDomain field.
func (o *EmailDetectData) SetPublicDomain(v bool) {
	o.PublicDomain = &v
}

// GetRelayDomain returns the RelayDomain field value if set, zero value otherwise.
func (o *EmailDetectData) GetRelayDomain() bool {
	if o == nil || IsNil(o.RelayDomain) {
		var ret bool
		return ret
	}
	return *o.RelayDomain
}

// GetRelayDomainOk returns a tuple with the RelayDomain field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EmailDetectData) GetRelayDomainOk() (*bool, bool) {
	if o == nil || IsNil(o.RelayDomain) {
		return nil, false
	}
	return o.RelayDomain, true
}

// HasRelayDomain returns a boolean if a field has been set.
func (o *EmailDetectData) HasRelayDomain() bool {
	if o != nil && !IsNil(o.RelayDomain) {
		return true
	}

	return false
}

// SetRelayDomain gets a reference to the given bool and assigns it to the RelayDomain field.
func (o *EmailDetectData) SetRelayDomain(v bool) {
	o.RelayDomain = &v
}

// GetRelayProvider returns the RelayProvider field value if set, zero value otherwise.
func (o *EmailDetectData) GetRelayProvider() string {
	if o == nil || IsNil(o.RelayProvider) {
		var ret string
		return ret
	}
	return *o.RelayProvider
}

// GetRelayProviderOk returns a tuple with the RelayProvider field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EmailDetectData) GetRelayProviderOk() (*string, bool) {
	if o == nil || IsNil(o.RelayProvider) {
		return nil, false
	}
	return o.RelayProvider, true
}

// HasRelayProvider returns a boolean if a field has been set.
func (o *EmailDetectData) HasRelayProvider() bool {
	if o != nil && !IsNil(o.RelayProvider) {
		return true
	}

	return false
}

// SetRelayProvider gets a reference to the given string and assigns it to the RelayProvider field.
func (o *EmailDetectData) SetRelayProvider(v string) {
	o.RelayProvider = &v
}

// GetRoleAddress returns the RoleAddress field value if set, zero value otherwise.
func (o *EmailDetectData) GetRoleAddress() bool {
	if o == nil || IsNil(o.RoleAddress) {
		var ret bool
		return ret
	}
	return *o.RoleAddress
}

// GetRoleAddressOk returns a tuple with the RoleAddress field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EmailDetectData) GetRoleAddressOk() (*bool, bool) {
	if o == nil || IsNil(o.RoleAddress) {
		return nil, false
	}
	return o.RoleAddress, true
}

// HasRoleAddress returns a boolean if a field has been set.
func (o *EmailDetectData) HasRoleAddress() bool {
	if o != nil && !IsNil(o.RoleAddress) {
		return true
	}

	return false
}

// SetRoleAddress gets a reference to the given bool and assigns it to the RoleAddress field.
func (o *EmailDetectData) SetRoleAddress(v bool) {
	o.RoleAddress = &v
}

// GetSubaddressing returns the Subaddressing field value if set, zero value otherwise.
func (o *EmailDetectData) GetSubaddressing() bool {
	if o == nil || IsNil(o.Subaddressing) {
		var ret bool
		return ret
	}
	return *o.Subaddressing
}

// GetSubaddressingOk returns a tuple with the Subaddressing field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EmailDetectData) GetSubaddressingOk() (*bool, bool) {
	if o == nil || IsNil(o.Subaddressing) {
		return nil, false
	}
	return o.Subaddressing, true
}

// HasSubaddressing returns a boolean if a field has been set.
func (o *EmailDetectData) HasSubaddressing() bool {
	if o != nil && !IsNil(o.Subaddressing) {
		return true
	}

	return false
}

// SetSubaddressing gets a reference to the given bool and assigns it to the Subaddressing field.
func (o *EmailDetectData) SetSubaddressing(v bool) {
	o.Subaddressing = &v
}

// GetSuggestedDomain returns the SuggestedDomain field value if set, zero value otherwise.
func (o *EmailDetectData) GetSuggestedDomain() string {
	if o == nil || IsNil(o.SuggestedDomain) {
		var ret string
		return ret
	}
	return *o.SuggestedDomain
}

// GetSuggestedDomainOk returns a tuple with the SuggestedDomain field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EmailDetectData) GetSuggestedDomainOk() (*string, bool) {
	if o == nil || IsNil(o.SuggestedDomain) {
		return nil, false
	}
	return o.SuggestedDomain, true
}

// HasSuggestedDomain returns a boolean if a field has been set.
func (o *EmailDetectData) HasSuggestedDomain() bool {
	if o != nil && !IsNil(o.SuggestedDomain) {
		return true
	}

	return false
}

// SetSuggestedDomain gets a reference to the given string and assigns it to the SuggestedDomain field.
func (o *EmailDetectData) SetSuggestedDomain(v string) {
	o.SuggestedDomain = &v
}

// GetSuggestedEmail returns the SuggestedEmail field value if set, zero value otherwise.
func (o *EmailDetectData) GetSuggestedEmail() string {
	if o == nil || IsNil(o.SuggestedEmail) {
		var ret string
		return ret
	}
	return *o.SuggestedEmail
}

// GetSuggestedEmailOk returns a tuple with the SuggestedEmail field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EmailDetectData) GetSuggestedEmailOk() (*string, bool) {
	if o == nil || IsNil(o.SuggestedEmail) {
		return nil, false
	}
	return o.SuggestedEmail, true
}

// HasSuggestedEmail returns a boolean if a field has been set.
func (o *EmailDetectData) HasSuggestedEmail() bool {
	if o != nil && !IsNil(o.SuggestedEmail) {
		return true
	}

	return false
}

// SetSuggestedEmail gets a reference to the given string and assigns it to the SuggestedEmail field.
func (o *EmailDetectData) SetSuggestedEmail(v string) {
	o.SuggestedEmail = &v
}

// GetSyntaxValidation returns the SyntaxValidation field value if set, zero value otherwise.
func (o *EmailDetectData) GetSyntaxValidation() bool {
	if o == nil || IsNil(o.SyntaxValidation) {
		var ret bool
		return ret
	}
	return *o.SyntaxValidation
}

// GetSyntaxValidationOk returns a tuple with the SyntaxValidation field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EmailDetectData) GetSyntaxValidationOk() (*bool, bool) {
	if o == nil || IsNil(o.SyntaxValidation) {
		return nil, false
	}
	return o.SyntaxValidation, true
}

// HasSyntaxValidation returns a boolean if a field has been set.
func (o *EmailDetectData) HasSyntaxValidation() bool {
	if o != nil && !IsNil(o.SyntaxValidation) {
		return true
	}

	return false
}

// SetSyntaxValidation gets a reference to the given bool and assigns it to the SyntaxValidation field.
func (o *EmailDetectData) SetSyntaxValidation(v bool) {
	o.SyntaxValidation = &v
}

func (o EmailDetectData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EmailDetectData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.DetectionSource) {
		toSerialize["detection_source"] = o.DetectionSource
	}
	if !IsNil(o.Disposable) {
		toSerialize["disposable"] = o.Disposable
	}
	if !IsNil(o.DisposableProvider) {
		toSerialize["disposable_provider"] = o.DisposableProvider
	}
	if !IsNil(o.Domain) {
		toSerialize["domain"] = o.Domain
	}
	if !IsNil(o.Email) {
		toSerialize["email"] = o.Email
	}
	if !IsNil(o.Normalized) {
		toSerialize["normalized"] = o.Normalized
	}
	if !IsNil(o.PublicDomain) {
		toSerialize["public_domain"] = o.PublicDomain
	}
	if !IsNil(o.RelayDomain) {
		toSerialize["relay_domain"] = o.RelayDomain
	}
	if !IsNil(o.RelayProvider) {
		toSerialize["relay_provider"] = o.RelayProvider
	}
	if !IsNil(o.RoleAddress) {
		toSerialize["role_address"] = o.RoleAddress
	}
	if !IsNil(o.Subaddressing) {
		toSerialize["subaddressing"] = o.Subaddressing
	}
	if !IsNil(o.SuggestedDomain) {
		toSerialize["suggested_domain"] = o.SuggestedDomain
	}
	if !IsNil(o.SuggestedEmail) {
		toSerialize["suggested_email"] = o.SuggestedEmail
	}
	if !IsNil(o.SyntaxValidation) {
		toSerialize["syntax_validation"] = o.SyntaxValidation
	}
	return toSerialize, nil
}

type NullableEmailDetectData struct {
	value *EmailDetectData
	isSet bool
}

func (v NullableEmailDetectData) Get() *EmailDetectData {
	return v.value
}

func (v *NullableEmailDetectData) Set(val *EmailDetectData) {
	v.value = val
	v.isSet = true
}

func (v NullableEmailDetectData) IsSet() bool {
	return v.isSet
}

func (v *NullableEmailDetectData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEmailDetectData(val *EmailDetectData) *NullableEmailDetectData {
	return &NullableEmailDetectData{value: val, isSet: true}
}

func (v NullableEmailDetectData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEmailDetectData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


