/*
EmailGuard Public API

Team-scoped REST API at /api/v1. Authenticate with `Authorization: Bearer egsk_live_...` or `X-API-Key`. Forks may register custom routes under /api/v1/tools/_* (requires `tools:read` / `tools:write` scopes). Async tool jobs return a `job_id` — poll `GET .../{jobId}/results` until complete. See /docs/api-reference.

API version: 1.0
Contact: dev@emailguard.co
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package emailguardsdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the GetNotificationEventsResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetNotificationEventsResponse{}

// GetNotificationEventsResponse struct for GetNotificationEventsResponse
type GetNotificationEventsResponse struct {
	// Machine-readable status code (for example OK or INVALID_BODY).
	Code string `json:"code"`
	Data []string `json:"data,omitempty"`
	// Human-readable detail when the code is not OK.
	Message *string `json:"message,omitempty"`
}

type _GetNotificationEventsResponse GetNotificationEventsResponse

// NewGetNotificationEventsResponse instantiates a new GetNotificationEventsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetNotificationEventsResponse(code string) *GetNotificationEventsResponse {
	this := GetNotificationEventsResponse{}
	this.Code = code
	return &this
}

// NewGetNotificationEventsResponseWithDefaults instantiates a new GetNotificationEventsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetNotificationEventsResponseWithDefaults() *GetNotificationEventsResponse {
	this := GetNotificationEventsResponse{}
	return &this
}

// GetCode returns the Code field value
func (o *GetNotificationEventsResponse) GetCode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Code
}

// GetCodeOk returns a tuple with the Code field value
// and a boolean to check if the value has been set.
func (o *GetNotificationEventsResponse) GetCodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Code, true
}

// SetCode sets field value
func (o *GetNotificationEventsResponse) SetCode(v string) {
	o.Code = v
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *GetNotificationEventsResponse) GetData() []string {
	if o == nil || IsNil(o.Data) {
		var ret []string
		return ret
	}
	return o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetNotificationEventsResponse) GetDataOk() ([]string, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *GetNotificationEventsResponse) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given []string and assigns it to the Data field.
func (o *GetNotificationEventsResponse) SetData(v []string) {
	o.Data = v
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *GetNotificationEventsResponse) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetNotificationEventsResponse) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *GetNotificationEventsResponse) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *GetNotificationEventsResponse) SetMessage(v string) {
	o.Message = &v
}

func (o GetNotificationEventsResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetNotificationEventsResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["code"] = o.Code
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	return toSerialize, nil
}

func (o *GetNotificationEventsResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"code",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGetNotificationEventsResponse := _GetNotificationEventsResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGetNotificationEventsResponse)

	if err != nil {
		return err
	}

	*o = GetNotificationEventsResponse(varGetNotificationEventsResponse)

	return err
}

type NullableGetNotificationEventsResponse struct {
	value *GetNotificationEventsResponse
	isSet bool
}

func (v NullableGetNotificationEventsResponse) Get() *GetNotificationEventsResponse {
	return v.value
}

func (v *NullableGetNotificationEventsResponse) Set(val *GetNotificationEventsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableGetNotificationEventsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableGetNotificationEventsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetNotificationEventsResponse(val *GetNotificationEventsResponse) *NullableGetNotificationEventsResponse {
	return &NullableGetNotificationEventsResponse{value: val, isSet: true}
}

func (v NullableGetNotificationEventsResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetNotificationEventsResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


