/*
EmailGuard Public API

Team-scoped REST API at /api/v1. Authenticate with `Authorization: Bearer egsk_live_...` or `X-API-Key`. Forks may register custom routes under /api/v1/tools/_* (requires `tools:read` / `tools:write` scopes). Async tool jobs return a `job_id` — poll `GET .../{jobId}/results` until complete. See /docs/api-reference.

API version: 1.0
Contact: dev@emailguard.co
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package emailguardsdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the PublicTeamInviteResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PublicTeamInviteResponse{}

// PublicTeamInviteResponse struct for PublicTeamInviteResponse
type PublicTeamInviteResponse struct {
	// Email address the invite was sent to.
	Email string `json:"email"`
	// When the invite expires if not accepted (RFC3339).
	ExpiresAt string `json:"expires_at"`
	// Invite record ID.
	Id string `json:"id"`
	// Role the invitee will receive when they accept.
	Role string `json:"role"`
}

type _PublicTeamInviteResponse PublicTeamInviteResponse

// NewPublicTeamInviteResponse instantiates a new PublicTeamInviteResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPublicTeamInviteResponse(email string, expiresAt string, id string, role string) *PublicTeamInviteResponse {
	this := PublicTeamInviteResponse{}
	this.Email = email
	this.ExpiresAt = expiresAt
	this.Id = id
	this.Role = role
	return &this
}

// NewPublicTeamInviteResponseWithDefaults instantiates a new PublicTeamInviteResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPublicTeamInviteResponseWithDefaults() *PublicTeamInviteResponse {
	this := PublicTeamInviteResponse{}
	return &this
}

// GetEmail returns the Email field value
func (o *PublicTeamInviteResponse) GetEmail() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Email
}

// GetEmailOk returns a tuple with the Email field value
// and a boolean to check if the value has been set.
func (o *PublicTeamInviteResponse) GetEmailOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Email, true
}

// SetEmail sets field value
func (o *PublicTeamInviteResponse) SetEmail(v string) {
	o.Email = v
}

// GetExpiresAt returns the ExpiresAt field value
func (o *PublicTeamInviteResponse) GetExpiresAt() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ExpiresAt
}

// GetExpiresAtOk returns a tuple with the ExpiresAt field value
// and a boolean to check if the value has been set.
func (o *PublicTeamInviteResponse) GetExpiresAtOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ExpiresAt, true
}

// SetExpiresAt sets field value
func (o *PublicTeamInviteResponse) SetExpiresAt(v string) {
	o.ExpiresAt = v
}

// GetId returns the Id field value
func (o *PublicTeamInviteResponse) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *PublicTeamInviteResponse) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *PublicTeamInviteResponse) SetId(v string) {
	o.Id = v
}

// GetRole returns the Role field value
func (o *PublicTeamInviteResponse) GetRole() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Role
}

// GetRoleOk returns a tuple with the Role field value
// and a boolean to check if the value has been set.
func (o *PublicTeamInviteResponse) GetRoleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Role, true
}

// SetRole sets field value
func (o *PublicTeamInviteResponse) SetRole(v string) {
	o.Role = v
}

func (o PublicTeamInviteResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PublicTeamInviteResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["email"] = o.Email
	toSerialize["expires_at"] = o.ExpiresAt
	toSerialize["id"] = o.Id
	toSerialize["role"] = o.Role
	return toSerialize, nil
}

func (o *PublicTeamInviteResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"email",
		"expires_at",
		"id",
		"role",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPublicTeamInviteResponse := _PublicTeamInviteResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPublicTeamInviteResponse)

	if err != nil {
		return err
	}

	*o = PublicTeamInviteResponse(varPublicTeamInviteResponse)

	return err
}

type NullablePublicTeamInviteResponse struct {
	value *PublicTeamInviteResponse
	isSet bool
}

func (v NullablePublicTeamInviteResponse) Get() *PublicTeamInviteResponse {
	return v.value
}

func (v *NullablePublicTeamInviteResponse) Set(val *PublicTeamInviteResponse) {
	v.value = val
	v.isSet = true
}

func (v NullablePublicTeamInviteResponse) IsSet() bool {
	return v.isSet
}

func (v *NullablePublicTeamInviteResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePublicTeamInviteResponse(val *PublicTeamInviteResponse) *NullablePublicTeamInviteResponse {
	return &NullablePublicTeamInviteResponse{value: val, isSet: true}
}

func (v NullablePublicTeamInviteResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePublicTeamInviteResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


