/*
EmailGuard Public API

Team-scoped REST API at /api/v1. Authenticate with `Authorization: Bearer egsk_live_...` or `X-API-Key`. Forks may register custom routes under /api/v1/tools/_* (requires `tools:read` / `tools:write` scopes). Async tool jobs return a `job_id` — poll `GET .../{jobId}/results` until complete. See /docs/api-reference.

API version: 1.0
Contact: dev@emailguard.co
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package emailguardsdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the UpdateTeamMemberInput type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateTeamMemberInput{}

// UpdateTeamMemberInput struct for UpdateTeamMemberInput
type UpdateTeamMemberInput struct {
	// Internal team member record ID. When calling the public API, this is set from the path userId.
	Id string `json:"id"`
	// Internal notes about the member. Omit to leave unchanged.
	Notes *string `json:"notes,omitempty"`
	// New team role (for example Owner, Admin, Member). Omit to leave unchanged. See [Team roles and permissions](/docs/knowledge-base/team-roles-and-permissions).
	Role *string `json:"role,omitempty"`
}

type _UpdateTeamMemberInput UpdateTeamMemberInput

// NewUpdateTeamMemberInput instantiates a new UpdateTeamMemberInput object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateTeamMemberInput(id string) *UpdateTeamMemberInput {
	this := UpdateTeamMemberInput{}
	this.Id = id
	return &this
}

// NewUpdateTeamMemberInputWithDefaults instantiates a new UpdateTeamMemberInput object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateTeamMemberInputWithDefaults() *UpdateTeamMemberInput {
	this := UpdateTeamMemberInput{}
	return &this
}

// GetId returns the Id field value
func (o *UpdateTeamMemberInput) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *UpdateTeamMemberInput) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *UpdateTeamMemberInput) SetId(v string) {
	o.Id = v
}

// GetNotes returns the Notes field value if set, zero value otherwise.
func (o *UpdateTeamMemberInput) GetNotes() string {
	if o == nil || IsNil(o.Notes) {
		var ret string
		return ret
	}
	return *o.Notes
}

// GetNotesOk returns a tuple with the Notes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateTeamMemberInput) GetNotesOk() (*string, bool) {
	if o == nil || IsNil(o.Notes) {
		return nil, false
	}
	return o.Notes, true
}

// HasNotes returns a boolean if a field has been set.
func (o *UpdateTeamMemberInput) HasNotes() bool {
	if o != nil && !IsNil(o.Notes) {
		return true
	}

	return false
}

// SetNotes gets a reference to the given string and assigns it to the Notes field.
func (o *UpdateTeamMemberInput) SetNotes(v string) {
	o.Notes = &v
}

// GetRole returns the Role field value if set, zero value otherwise.
func (o *UpdateTeamMemberInput) GetRole() string {
	if o == nil || IsNil(o.Role) {
		var ret string
		return ret
	}
	return *o.Role
}

// GetRoleOk returns a tuple with the Role field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateTeamMemberInput) GetRoleOk() (*string, bool) {
	if o == nil || IsNil(o.Role) {
		return nil, false
	}
	return o.Role, true
}

// HasRole returns a boolean if a field has been set.
func (o *UpdateTeamMemberInput) HasRole() bool {
	if o != nil && !IsNil(o.Role) {
		return true
	}

	return false
}

// SetRole gets a reference to the given string and assigns it to the Role field.
func (o *UpdateTeamMemberInput) SetRole(v string) {
	o.Role = &v
}

func (o UpdateTeamMemberInput) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateTeamMemberInput) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	if !IsNil(o.Notes) {
		toSerialize["notes"] = o.Notes
	}
	if !IsNil(o.Role) {
		toSerialize["role"] = o.Role
	}
	return toSerialize, nil
}

func (o *UpdateTeamMemberInput) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUpdateTeamMemberInput := _UpdateTeamMemberInput{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUpdateTeamMemberInput)

	if err != nil {
		return err
	}

	*o = UpdateTeamMemberInput(varUpdateTeamMemberInput)

	return err
}

type NullableUpdateTeamMemberInput struct {
	value *UpdateTeamMemberInput
	isSet bool
}

func (v NullableUpdateTeamMemberInput) Get() *UpdateTeamMemberInput {
	return v.value
}

func (v *NullableUpdateTeamMemberInput) Set(val *UpdateTeamMemberInput) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateTeamMemberInput) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateTeamMemberInput) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateTeamMemberInput(val *UpdateTeamMemberInput) *NullableUpdateTeamMemberInput {
	return &NullableUpdateTeamMemberInput{value: val, isSet: true}
}

func (v NullableUpdateTeamMemberInput) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateTeamMemberInput) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


