/*
EmailGuard Public API

Team-scoped REST API at /api/v1. Authenticate with `Authorization: Bearer egsk_live_...` or `X-API-Key`. Forks may register custom routes under /api/v1/tools/_* (requires `tools:read` / `tools:write` scopes). Async tool jobs return a `job_id` — poll `GET .../{jobId}/results` until complete. See /docs/api-reference.

API version: 1.0
Contact: dev@emailguard.co
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package emailguardsdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the BillingUsageEvent type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BillingUsageEvent{}

// BillingUsageEvent struct for BillingUsageEvent
type BillingUsageEvent struct {
	Delta int32 `json:"delta"`
	EventType string `json:"event_type"`
	Metadata string `json:"metadata"`
	UsageAfter int32 `json:"usage_after"`
	UsageBefore int32 `json:"usage_before"`
}

type _BillingUsageEvent BillingUsageEvent

// NewBillingUsageEvent instantiates a new BillingUsageEvent object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBillingUsageEvent(delta int32, eventType string, metadata string, usageAfter int32, usageBefore int32) *BillingUsageEvent {
	this := BillingUsageEvent{}
	this.Delta = delta
	this.EventType = eventType
	this.Metadata = metadata
	this.UsageAfter = usageAfter
	this.UsageBefore = usageBefore
	return &this
}

// NewBillingUsageEventWithDefaults instantiates a new BillingUsageEvent object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBillingUsageEventWithDefaults() *BillingUsageEvent {
	this := BillingUsageEvent{}
	return &this
}

// GetDelta returns the Delta field value
func (o *BillingUsageEvent) GetDelta() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Delta
}

// GetDeltaOk returns a tuple with the Delta field value
// and a boolean to check if the value has been set.
func (o *BillingUsageEvent) GetDeltaOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Delta, true
}

// SetDelta sets field value
func (o *BillingUsageEvent) SetDelta(v int32) {
	o.Delta = v
}

// GetEventType returns the EventType field value
func (o *BillingUsageEvent) GetEventType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.EventType
}

// GetEventTypeOk returns a tuple with the EventType field value
// and a boolean to check if the value has been set.
func (o *BillingUsageEvent) GetEventTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.EventType, true
}

// SetEventType sets field value
func (o *BillingUsageEvent) SetEventType(v string) {
	o.EventType = v
}

// GetMetadata returns the Metadata field value
func (o *BillingUsageEvent) GetMetadata() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Metadata
}

// GetMetadataOk returns a tuple with the Metadata field value
// and a boolean to check if the value has been set.
func (o *BillingUsageEvent) GetMetadataOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Metadata, true
}

// SetMetadata sets field value
func (o *BillingUsageEvent) SetMetadata(v string) {
	o.Metadata = v
}

// GetUsageAfter returns the UsageAfter field value
func (o *BillingUsageEvent) GetUsageAfter() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.UsageAfter
}

// GetUsageAfterOk returns a tuple with the UsageAfter field value
// and a boolean to check if the value has been set.
func (o *BillingUsageEvent) GetUsageAfterOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UsageAfter, true
}

// SetUsageAfter sets field value
func (o *BillingUsageEvent) SetUsageAfter(v int32) {
	o.UsageAfter = v
}

// GetUsageBefore returns the UsageBefore field value
func (o *BillingUsageEvent) GetUsageBefore() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.UsageBefore
}

// GetUsageBeforeOk returns a tuple with the UsageBefore field value
// and a boolean to check if the value has been set.
func (o *BillingUsageEvent) GetUsageBeforeOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UsageBefore, true
}

// SetUsageBefore sets field value
func (o *BillingUsageEvent) SetUsageBefore(v int32) {
	o.UsageBefore = v
}

func (o BillingUsageEvent) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BillingUsageEvent) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["delta"] = o.Delta
	toSerialize["event_type"] = o.EventType
	toSerialize["metadata"] = o.Metadata
	toSerialize["usage_after"] = o.UsageAfter
	toSerialize["usage_before"] = o.UsageBefore
	return toSerialize, nil
}

func (o *BillingUsageEvent) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"delta",
		"event_type",
		"metadata",
		"usage_after",
		"usage_before",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varBillingUsageEvent := _BillingUsageEvent{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varBillingUsageEvent)

	if err != nil {
		return err
	}

	*o = BillingUsageEvent(varBillingUsageEvent)

	return err
}

type NullableBillingUsageEvent struct {
	value *BillingUsageEvent
	isSet bool
}

func (v NullableBillingUsageEvent) Get() *BillingUsageEvent {
	return v.value
}

func (v *NullableBillingUsageEvent) Set(val *BillingUsageEvent) {
	v.value = val
	v.isSet = true
}

func (v NullableBillingUsageEvent) IsSet() bool {
	return v.isSet
}

func (v *NullableBillingUsageEvent) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBillingUsageEvent(val *BillingUsageEvent) *NullableBillingUsageEvent {
	return &NullableBillingUsageEvent{value: val, isSet: true}
}

func (v NullableBillingUsageEvent) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBillingUsageEvent) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


