// Code generated by scripts/clients/generate-go-facade.mjs; DO NOT EDIT.
package emailguardsdk

import "github.com/EmailGuard/emailguard-go/internal/openapi"

type BaseResponse = openapi.BaseResponse
type BillingUsageEvent = openapi.BillingUsageEvent
type BillingUsageItem = openapi.BillingUsageItem
type BillingUsageResponse = openapi.BillingUsageResponse
type CreateNotificationChannelInput = openapi.CreateNotificationChannelInput
type CreateNotificationRuleInput = openapi.CreateNotificationRuleInput
type EmailDetectData = openapi.EmailDetectData
type EmailDetectEvidence = openapi.EmailDetectEvidence
type EmailDetectMatchedRule = openapi.EmailDetectMatchedRule
type EmailDetectResponse = openapi.EmailDetectResponse
type GetNotificationChannelResponse = openapi.GetNotificationChannelResponse
type GetNotificationChannelsResponse = openapi.GetNotificationChannelsResponse
type GetNotificationEventsResponse = openapi.GetNotificationEventsResponse
type GetNotificationRulesResponse = openapi.GetNotificationRulesResponse
type GetPublicTeamResponse = openapi.GetPublicTeamResponse
type IdDataResponse = openapi.IdDataResponse
type IdDataStruct = openapi.IdDataStruct
type InviteTeamMemberInput = openapi.InviteTeamMemberInput
type ListPublicTeamInvitesResponse = openapi.ListPublicTeamInvitesResponse
type ListPublicTeamMembersResponse = openapi.ListPublicTeamMembersResponse
type MessageResponse = openapi.MessageResponse
type NotificationChannelResponse = openapi.NotificationChannelResponse
type NotificationRuleChannelInput = openapi.NotificationRuleChannelInput
type NotificationRuleChannelResponse = openapi.NotificationRuleChannelResponse
type NotificationRuleResponse = openapi.NotificationRuleResponse
type PublicTeamInviteResponse = openapi.PublicTeamInviteResponse
type PublicTeamMemberResponse = openapi.PublicTeamMemberResponse
type PublicTeamResponse = openapi.PublicTeamResponse
type PublicUpdateTeamMemberInput = openapi.PublicUpdateTeamMemberInput
type UpdateNotificationChannelInput = openapi.UpdateNotificationChannelInput
type UpdateNotificationRuleInput = openapi.UpdateNotificationRuleInput
type UpdateTeamInput = openapi.UpdateTeamInput
