/*
EmailGuard Public API

Team-scoped REST API at /api/v1. Authenticate with `Authorization: Bearer egsk_live_...` or `X-API-Key`. Forks may register custom routes under /api/v1/tools/_* (requires `tools:read` / `tools:write` scopes). Async tool jobs return a `job_id` — poll `GET .../{jobId}/results` until complete. See /docs/api-reference.

API version: 1.0
Contact: dev@emailguard.co
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package emailguardsdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the BillingUsageResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BillingUsageResponse{}

// BillingUsageResponse struct for BillingUsageResponse
type BillingUsageResponse struct {
	// Machine-readable status code (for example OK or INVALID_BODY).
	Code string `json:"code"`
	Data []BillingUsageItem `json:"data,omitempty"`
	// Human-readable detail when the code is not OK.
	Message *string `json:"message,omitempty"`
}

type _BillingUsageResponse BillingUsageResponse

// NewBillingUsageResponse instantiates a new BillingUsageResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBillingUsageResponse(code string) *BillingUsageResponse {
	this := BillingUsageResponse{}
	this.Code = code
	return &this
}

// NewBillingUsageResponseWithDefaults instantiates a new BillingUsageResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBillingUsageResponseWithDefaults() *BillingUsageResponse {
	this := BillingUsageResponse{}
	return &this
}

// GetCode returns the Code field value
func (o *BillingUsageResponse) GetCode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Code
}

// GetCodeOk returns a tuple with the Code field value
// and a boolean to check if the value has been set.
func (o *BillingUsageResponse) GetCodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Code, true
}

// SetCode sets field value
func (o *BillingUsageResponse) SetCode(v string) {
	o.Code = v
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *BillingUsageResponse) GetData() []BillingUsageItem {
	if o == nil || IsNil(o.Data) {
		var ret []BillingUsageItem
		return ret
	}
	return o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BillingUsageResponse) GetDataOk() ([]BillingUsageItem, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *BillingUsageResponse) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given []BillingUsageItem and assigns it to the Data field.
func (o *BillingUsageResponse) SetData(v []BillingUsageItem) {
	o.Data = v
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *BillingUsageResponse) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BillingUsageResponse) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *BillingUsageResponse) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *BillingUsageResponse) SetMessage(v string) {
	o.Message = &v
}

func (o BillingUsageResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BillingUsageResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["code"] = o.Code
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	return toSerialize, nil
}

func (o *BillingUsageResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"code",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varBillingUsageResponse := _BillingUsageResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varBillingUsageResponse)

	if err != nil {
		return err
	}

	*o = BillingUsageResponse(varBillingUsageResponse)

	return err
}

type NullableBillingUsageResponse struct {
	value *BillingUsageResponse
	isSet bool
}

func (v NullableBillingUsageResponse) Get() *BillingUsageResponse {
	return v.value
}

func (v *NullableBillingUsageResponse) Set(val *BillingUsageResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableBillingUsageResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableBillingUsageResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBillingUsageResponse(val *BillingUsageResponse) *NullableBillingUsageResponse {
	return &NullableBillingUsageResponse{value: val, isSet: true}
}

func (v NullableBillingUsageResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBillingUsageResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


