/*
EmailGuard Public API

Team-scoped REST API at /api/v1. Authenticate with `Authorization: Bearer egsk_live_...` or `X-API-Key`. Forks may register custom routes under /api/v1/tools/_* (requires `tools:read` / `tools:write` scopes). Async tool jobs return a `job_id` — poll `GET .../{jobId}/results` until complete. See /docs/api-reference.

API version: 1.0
Contact: dev@emailguard.co
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package emailguardsdk

import (
	"encoding/json"
)

// checks if the NotificationRuleChannelResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &NotificationRuleChannelResponse{}

// NotificationRuleChannelResponse struct for NotificationRuleChannelResponse
type NotificationRuleChannelResponse struct {
	// Linked custom channel ID, if any.
	ChannelId *string `json:"channel_id,omitempty"`
	// Name of the linked channel, when resolved.
	ChannelName *string `json:"channel_name,omitempty"`
	// Type of the linked channel, when resolved.
	ChannelType *string `json:"channel_type,omitempty"`
	// Assignment record ID.
	Id *string `json:"id,omitempty"`
	// Built-in channel identifier when not using a custom channel.
	Predefined *string `json:"predefined,omitempty"`
	// User ID when delivery is scoped to one member.
	TargetUserId *string `json:"target_user_id,omitempty"`
}

// NewNotificationRuleChannelResponse instantiates a new NotificationRuleChannelResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNotificationRuleChannelResponse() *NotificationRuleChannelResponse {
	this := NotificationRuleChannelResponse{}
	return &this
}

// NewNotificationRuleChannelResponseWithDefaults instantiates a new NotificationRuleChannelResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNotificationRuleChannelResponseWithDefaults() *NotificationRuleChannelResponse {
	this := NotificationRuleChannelResponse{}
	return &this
}

// GetChannelId returns the ChannelId field value if set, zero value otherwise.
func (o *NotificationRuleChannelResponse) GetChannelId() string {
	if o == nil || IsNil(o.ChannelId) {
		var ret string
		return ret
	}
	return *o.ChannelId
}

// GetChannelIdOk returns a tuple with the ChannelId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NotificationRuleChannelResponse) GetChannelIdOk() (*string, bool) {
	if o == nil || IsNil(o.ChannelId) {
		return nil, false
	}
	return o.ChannelId, true
}

// HasChannelId returns a boolean if a field has been set.
func (o *NotificationRuleChannelResponse) HasChannelId() bool {
	if o != nil && !IsNil(o.ChannelId) {
		return true
	}

	return false
}

// SetChannelId gets a reference to the given string and assigns it to the ChannelId field.
func (o *NotificationRuleChannelResponse) SetChannelId(v string) {
	o.ChannelId = &v
}

// GetChannelName returns the ChannelName field value if set, zero value otherwise.
func (o *NotificationRuleChannelResponse) GetChannelName() string {
	if o == nil || IsNil(o.ChannelName) {
		var ret string
		return ret
	}
	return *o.ChannelName
}

// GetChannelNameOk returns a tuple with the ChannelName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NotificationRuleChannelResponse) GetChannelNameOk() (*string, bool) {
	if o == nil || IsNil(o.ChannelName) {
		return nil, false
	}
	return o.ChannelName, true
}

// HasChannelName returns a boolean if a field has been set.
func (o *NotificationRuleChannelResponse) HasChannelName() bool {
	if o != nil && !IsNil(o.ChannelName) {
		return true
	}

	return false
}

// SetChannelName gets a reference to the given string and assigns it to the ChannelName field.
func (o *NotificationRuleChannelResponse) SetChannelName(v string) {
	o.ChannelName = &v
}

// GetChannelType returns the ChannelType field value if set, zero value otherwise.
func (o *NotificationRuleChannelResponse) GetChannelType() string {
	if o == nil || IsNil(o.ChannelType) {
		var ret string
		return ret
	}
	return *o.ChannelType
}

// GetChannelTypeOk returns a tuple with the ChannelType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NotificationRuleChannelResponse) GetChannelTypeOk() (*string, bool) {
	if o == nil || IsNil(o.ChannelType) {
		return nil, false
	}
	return o.ChannelType, true
}

// HasChannelType returns a boolean if a field has been set.
func (o *NotificationRuleChannelResponse) HasChannelType() bool {
	if o != nil && !IsNil(o.ChannelType) {
		return true
	}

	return false
}

// SetChannelType gets a reference to the given string and assigns it to the ChannelType field.
func (o *NotificationRuleChannelResponse) SetChannelType(v string) {
	o.ChannelType = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *NotificationRuleChannelResponse) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NotificationRuleChannelResponse) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *NotificationRuleChannelResponse) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *NotificationRuleChannelResponse) SetId(v string) {
	o.Id = &v
}

// GetPredefined returns the Predefined field value if set, zero value otherwise.
func (o *NotificationRuleChannelResponse) GetPredefined() string {
	if o == nil || IsNil(o.Predefined) {
		var ret string
		return ret
	}
	return *o.Predefined
}

// GetPredefinedOk returns a tuple with the Predefined field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NotificationRuleChannelResponse) GetPredefinedOk() (*string, bool) {
	if o == nil || IsNil(o.Predefined) {
		return nil, false
	}
	return o.Predefined, true
}

// HasPredefined returns a boolean if a field has been set.
func (o *NotificationRuleChannelResponse) HasPredefined() bool {
	if o != nil && !IsNil(o.Predefined) {
		return true
	}

	return false
}

// SetPredefined gets a reference to the given string and assigns it to the Predefined field.
func (o *NotificationRuleChannelResponse) SetPredefined(v string) {
	o.Predefined = &v
}

// GetTargetUserId returns the TargetUserId field value if set, zero value otherwise.
func (o *NotificationRuleChannelResponse) GetTargetUserId() string {
	if o == nil || IsNil(o.TargetUserId) {
		var ret string
		return ret
	}
	return *o.TargetUserId
}

// GetTargetUserIdOk returns a tuple with the TargetUserId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NotificationRuleChannelResponse) GetTargetUserIdOk() (*string, bool) {
	if o == nil || IsNil(o.TargetUserId) {
		return nil, false
	}
	return o.TargetUserId, true
}

// HasTargetUserId returns a boolean if a field has been set.
func (o *NotificationRuleChannelResponse) HasTargetUserId() bool {
	if o != nil && !IsNil(o.TargetUserId) {
		return true
	}

	return false
}

// SetTargetUserId gets a reference to the given string and assigns it to the TargetUserId field.
func (o *NotificationRuleChannelResponse) SetTargetUserId(v string) {
	o.TargetUserId = &v
}

func (o NotificationRuleChannelResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o NotificationRuleChannelResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ChannelId) {
		toSerialize["channel_id"] = o.ChannelId
	}
	if !IsNil(o.ChannelName) {
		toSerialize["channel_name"] = o.ChannelName
	}
	if !IsNil(o.ChannelType) {
		toSerialize["channel_type"] = o.ChannelType
	}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Predefined) {
		toSerialize["predefined"] = o.Predefined
	}
	if !IsNil(o.TargetUserId) {
		toSerialize["target_user_id"] = o.TargetUserId
	}
	return toSerialize, nil
}

type NullableNotificationRuleChannelResponse struct {
	value *NotificationRuleChannelResponse
	isSet bool
}

func (v NullableNotificationRuleChannelResponse) Get() *NotificationRuleChannelResponse {
	return v.value
}

func (v *NullableNotificationRuleChannelResponse) Set(val *NotificationRuleChannelResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableNotificationRuleChannelResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableNotificationRuleChannelResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNotificationRuleChannelResponse(val *NotificationRuleChannelResponse) *NullableNotificationRuleChannelResponse {
	return &NullableNotificationRuleChannelResponse{value: val, isSet: true}
}

func (v NullableNotificationRuleChannelResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNotificationRuleChannelResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


