/*
EmailGuard Public API

Team-scoped REST API at /api/v1. Authenticate with `Authorization: Bearer egsk_live_...` or `X-API-Key`. Forks may register custom routes under /api/v1/tools/_* (requires `tools:read` / `tools:write` scopes). Async tool jobs return a `job_id` — poll `GET .../{jobId}/results` until complete. See /docs/api-reference.

API version: 1.0
Contact: dev@emailguard.co
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package emailguardsdk

import (
	"encoding/json"
)

// checks if the UpdateNotificationChannelInput type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateNotificationChannelInput{}

// UpdateNotificationChannelInput struct for UpdateNotificationChannelInput
type UpdateNotificationChannelInput struct {
	// Updated type-specific configuration. Omit to leave unchanged.
	Config map[string]interface{} `json:"config,omitempty"`
	// Updated display name. Omit to leave unchanged.
	Name *string `json:"name,omitempty"`
}

// NewUpdateNotificationChannelInput instantiates a new UpdateNotificationChannelInput object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateNotificationChannelInput() *UpdateNotificationChannelInput {
	this := UpdateNotificationChannelInput{}
	return &this
}

// NewUpdateNotificationChannelInputWithDefaults instantiates a new UpdateNotificationChannelInput object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateNotificationChannelInputWithDefaults() *UpdateNotificationChannelInput {
	this := UpdateNotificationChannelInput{}
	return &this
}

// GetConfig returns the Config field value if set, zero value otherwise.
func (o *UpdateNotificationChannelInput) GetConfig() map[string]interface{} {
	if o == nil || IsNil(o.Config) {
		var ret map[string]interface{}
		return ret
	}
	return o.Config
}

// GetConfigOk returns a tuple with the Config field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateNotificationChannelInput) GetConfigOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.Config) {
		return map[string]interface{}{}, false
	}
	return o.Config, true
}

// HasConfig returns a boolean if a field has been set.
func (o *UpdateNotificationChannelInput) HasConfig() bool {
	if o != nil && !IsNil(o.Config) {
		return true
	}

	return false
}

// SetConfig gets a reference to the given map[string]interface{} and assigns it to the Config field.
func (o *UpdateNotificationChannelInput) SetConfig(v map[string]interface{}) {
	o.Config = v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *UpdateNotificationChannelInput) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateNotificationChannelInput) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *UpdateNotificationChannelInput) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *UpdateNotificationChannelInput) SetName(v string) {
	o.Name = &v
}

func (o UpdateNotificationChannelInput) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateNotificationChannelInput) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Config) {
		toSerialize["config"] = o.Config
	}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	return toSerialize, nil
}

type NullableUpdateNotificationChannelInput struct {
	value *UpdateNotificationChannelInput
	isSet bool
}

func (v NullableUpdateNotificationChannelInput) Get() *UpdateNotificationChannelInput {
	return v.value
}

func (v *NullableUpdateNotificationChannelInput) Set(val *UpdateNotificationChannelInput) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateNotificationChannelInput) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateNotificationChannelInput) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateNotificationChannelInput(val *UpdateNotificationChannelInput) *NullableUpdateNotificationChannelInput {
	return &NullableUpdateNotificationChannelInput{value: val, isSet: true}
}

func (v NullableUpdateNotificationChannelInput) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateNotificationChannelInput) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


