/*
EmailGuard Public API

Team-scoped REST API at /api/v1. Authenticate with `Authorization: Bearer egsk_live_...` or `X-API-Key`. Forks may register custom routes under /api/v1/tools/_* (requires `tools:read` / `tools:write` scopes). Async tool jobs return a `job_id` — poll `GET .../{jobId}/results` until complete. See /docs/api-reference.

API version: 1.0
Contact: dev@emailguard.co
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package emailguardsdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the BillingUsageItem type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BillingUsageItem{}

// BillingUsageItem struct for BillingUsageItem
type BillingUsageItem struct {
	Events []BillingUsageEvent `json:"events,omitempty"`
	FeatureKey string `json:"feature_key"`
	Limit *int32 `json:"limit,omitempty"`
	PeriodEnd string `json:"period_end"`
	PeriodStart string `json:"period_start"`
	Usage int32 `json:"usage"`
}

type _BillingUsageItem BillingUsageItem

// NewBillingUsageItem instantiates a new BillingUsageItem object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBillingUsageItem(featureKey string, periodEnd string, periodStart string, usage int32) *BillingUsageItem {
	this := BillingUsageItem{}
	this.FeatureKey = featureKey
	this.PeriodEnd = periodEnd
	this.PeriodStart = periodStart
	this.Usage = usage
	return &this
}

// NewBillingUsageItemWithDefaults instantiates a new BillingUsageItem object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBillingUsageItemWithDefaults() *BillingUsageItem {
	this := BillingUsageItem{}
	return &this
}

// GetEvents returns the Events field value if set, zero value otherwise.
func (o *BillingUsageItem) GetEvents() []BillingUsageEvent {
	if o == nil || IsNil(o.Events) {
		var ret []BillingUsageEvent
		return ret
	}
	return o.Events
}

// GetEventsOk returns a tuple with the Events field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BillingUsageItem) GetEventsOk() ([]BillingUsageEvent, bool) {
	if o == nil || IsNil(o.Events) {
		return nil, false
	}
	return o.Events, true
}

// HasEvents returns a boolean if a field has been set.
func (o *BillingUsageItem) HasEvents() bool {
	if o != nil && !IsNil(o.Events) {
		return true
	}

	return false
}

// SetEvents gets a reference to the given []BillingUsageEvent and assigns it to the Events field.
func (o *BillingUsageItem) SetEvents(v []BillingUsageEvent) {
	o.Events = v
}

// GetFeatureKey returns the FeatureKey field value
func (o *BillingUsageItem) GetFeatureKey() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.FeatureKey
}

// GetFeatureKeyOk returns a tuple with the FeatureKey field value
// and a boolean to check if the value has been set.
func (o *BillingUsageItem) GetFeatureKeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.FeatureKey, true
}

// SetFeatureKey sets field value
func (o *BillingUsageItem) SetFeatureKey(v string) {
	o.FeatureKey = v
}

// GetLimit returns the Limit field value if set, zero value otherwise.
func (o *BillingUsageItem) GetLimit() int32 {
	if o == nil || IsNil(o.Limit) {
		var ret int32
		return ret
	}
	return *o.Limit
}

// GetLimitOk returns a tuple with the Limit field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BillingUsageItem) GetLimitOk() (*int32, bool) {
	if o == nil || IsNil(o.Limit) {
		return nil, false
	}
	return o.Limit, true
}

// HasLimit returns a boolean if a field has been set.
func (o *BillingUsageItem) HasLimit() bool {
	if o != nil && !IsNil(o.Limit) {
		return true
	}

	return false
}

// SetLimit gets a reference to the given int32 and assigns it to the Limit field.
func (o *BillingUsageItem) SetLimit(v int32) {
	o.Limit = &v
}

// GetPeriodEnd returns the PeriodEnd field value
func (o *BillingUsageItem) GetPeriodEnd() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PeriodEnd
}

// GetPeriodEndOk returns a tuple with the PeriodEnd field value
// and a boolean to check if the value has been set.
func (o *BillingUsageItem) GetPeriodEndOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PeriodEnd, true
}

// SetPeriodEnd sets field value
func (o *BillingUsageItem) SetPeriodEnd(v string) {
	o.PeriodEnd = v
}

// GetPeriodStart returns the PeriodStart field value
func (o *BillingUsageItem) GetPeriodStart() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.PeriodStart
}

// GetPeriodStartOk returns a tuple with the PeriodStart field value
// and a boolean to check if the value has been set.
func (o *BillingUsageItem) GetPeriodStartOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.PeriodStart, true
}

// SetPeriodStart sets field value
func (o *BillingUsageItem) SetPeriodStart(v string) {
	o.PeriodStart = v
}

// GetUsage returns the Usage field value
func (o *BillingUsageItem) GetUsage() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Usage
}

// GetUsageOk returns a tuple with the Usage field value
// and a boolean to check if the value has been set.
func (o *BillingUsageItem) GetUsageOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Usage, true
}

// SetUsage sets field value
func (o *BillingUsageItem) SetUsage(v int32) {
	o.Usage = v
}

func (o BillingUsageItem) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BillingUsageItem) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Events) {
		toSerialize["events"] = o.Events
	}
	toSerialize["feature_key"] = o.FeatureKey
	if !IsNil(o.Limit) {
		toSerialize["limit"] = o.Limit
	}
	toSerialize["period_end"] = o.PeriodEnd
	toSerialize["period_start"] = o.PeriodStart
	toSerialize["usage"] = o.Usage
	return toSerialize, nil
}

func (o *BillingUsageItem) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"feature_key",
		"period_end",
		"period_start",
		"usage",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varBillingUsageItem := _BillingUsageItem{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varBillingUsageItem)

	if err != nil {
		return err
	}

	*o = BillingUsageItem(varBillingUsageItem)

	return err
}

type NullableBillingUsageItem struct {
	value *BillingUsageItem
	isSet bool
}

func (v NullableBillingUsageItem) Get() *BillingUsageItem {
	return v.value
}

func (v *NullableBillingUsageItem) Set(val *BillingUsageItem) {
	v.value = val
	v.isSet = true
}

func (v NullableBillingUsageItem) IsSet() bool {
	return v.isSet
}

func (v *NullableBillingUsageItem) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBillingUsageItem(val *BillingUsageItem) *NullableBillingUsageItem {
	return &NullableBillingUsageItem{value: val, isSet: true}
}

func (v NullableBillingUsageItem) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBillingUsageItem) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


