/*
EmailGuard Public API

Team-scoped REST API at /api/v1. Authenticate with `Authorization: Bearer egsk_live_...` or `X-API-Key`. Forks may register custom routes under /api/v1/tools/_* (requires `tools:read` / `tools:write` scopes). Async tool jobs return a `job_id` — poll `GET .../{jobId}/results` until complete. See /docs/api-reference.

API version: 1.0
Contact: dev@emailguard.co
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package emailguardsdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the IdDataResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &IdDataResponse{}

// IdDataResponse struct for IdDataResponse
type IdDataResponse struct {
	// Machine-readable status code (for example OK or INVALID_BODY).
	Code string `json:"code"`
	Data *IdDataStruct `json:"data,omitempty"`
	// Human-readable detail when the code is not OK.
	Message *string `json:"message,omitempty"`
}

type _IdDataResponse IdDataResponse

// NewIdDataResponse instantiates a new IdDataResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewIdDataResponse(code string) *IdDataResponse {
	this := IdDataResponse{}
	this.Code = code
	return &this
}

// NewIdDataResponseWithDefaults instantiates a new IdDataResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewIdDataResponseWithDefaults() *IdDataResponse {
	this := IdDataResponse{}
	return &this
}

// GetCode returns the Code field value
func (o *IdDataResponse) GetCode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Code
}

// GetCodeOk returns a tuple with the Code field value
// and a boolean to check if the value has been set.
func (o *IdDataResponse) GetCodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Code, true
}

// SetCode sets field value
func (o *IdDataResponse) SetCode(v string) {
	o.Code = v
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *IdDataResponse) GetData() IdDataStruct {
	if o == nil || IsNil(o.Data) {
		var ret IdDataStruct
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IdDataResponse) GetDataOk() (*IdDataStruct, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *IdDataResponse) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given IdDataStruct and assigns it to the Data field.
func (o *IdDataResponse) SetData(v IdDataStruct) {
	o.Data = &v
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *IdDataResponse) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *IdDataResponse) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *IdDataResponse) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *IdDataResponse) SetMessage(v string) {
	o.Message = &v
}

func (o IdDataResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o IdDataResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["code"] = o.Code
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	return toSerialize, nil
}

func (o *IdDataResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"code",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varIdDataResponse := _IdDataResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varIdDataResponse)

	if err != nil {
		return err
	}

	*o = IdDataResponse(varIdDataResponse)

	return err
}

type NullableIdDataResponse struct {
	value *IdDataResponse
	isSet bool
}

func (v NullableIdDataResponse) Get() *IdDataResponse {
	return v.value
}

func (v *NullableIdDataResponse) Set(val *IdDataResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableIdDataResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableIdDataResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableIdDataResponse(val *IdDataResponse) *NullableIdDataResponse {
	return &NullableIdDataResponse{value: val, isSet: true}
}

func (v NullableIdDataResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableIdDataResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


