/*
EmailGuard Public API

Team-scoped REST API at /api/v1. Authenticate with `Authorization: Bearer egsk_live_...` or `X-API-Key`. Forks may register custom routes under /api/v1/tools/_* (requires `tools:read` / `tools:write` scopes). Async tool jobs return a `job_id` — poll `GET .../{jobId}/results` until complete. See /docs/api-reference.

API version: 1.1
Contact: dev@emailguard.co
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package emailguardsdk

import (
	"encoding/json"
)

// checks if the EmailDetectEvidence type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EmailDetectEvidence{}

// EmailDetectEvidence struct for EmailDetectEvidence
type EmailDetectEvidence struct {
	ClusterProvider *string `json:"cluster_provider,omitempty"`
	DetectionLayer *string `json:"detection_layer,omitempty"`
	SourceCount *int32 `json:"source_count,omitempty"`
}

// NewEmailDetectEvidence instantiates a new EmailDetectEvidence object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEmailDetectEvidence() *EmailDetectEvidence {
	this := EmailDetectEvidence{}
	return &this
}

// NewEmailDetectEvidenceWithDefaults instantiates a new EmailDetectEvidence object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEmailDetectEvidenceWithDefaults() *EmailDetectEvidence {
	this := EmailDetectEvidence{}
	return &this
}

// GetClusterProvider returns the ClusterProvider field value if set, zero value otherwise.
func (o *EmailDetectEvidence) GetClusterProvider() string {
	if o == nil || IsNil(o.ClusterProvider) {
		var ret string
		return ret
	}
	return *o.ClusterProvider
}

// GetClusterProviderOk returns a tuple with the ClusterProvider field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EmailDetectEvidence) GetClusterProviderOk() (*string, bool) {
	if o == nil || IsNil(o.ClusterProvider) {
		return nil, false
	}
	return o.ClusterProvider, true
}

// HasClusterProvider returns a boolean if a field has been set.
func (o *EmailDetectEvidence) HasClusterProvider() bool {
	if o != nil && !IsNil(o.ClusterProvider) {
		return true
	}

	return false
}

// SetClusterProvider gets a reference to the given string and assigns it to the ClusterProvider field.
func (o *EmailDetectEvidence) SetClusterProvider(v string) {
	o.ClusterProvider = &v
}

// GetDetectionLayer returns the DetectionLayer field value if set, zero value otherwise.
func (o *EmailDetectEvidence) GetDetectionLayer() string {
	if o == nil || IsNil(o.DetectionLayer) {
		var ret string
		return ret
	}
	return *o.DetectionLayer
}

// GetDetectionLayerOk returns a tuple with the DetectionLayer field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EmailDetectEvidence) GetDetectionLayerOk() (*string, bool) {
	if o == nil || IsNil(o.DetectionLayer) {
		return nil, false
	}
	return o.DetectionLayer, true
}

// HasDetectionLayer returns a boolean if a field has been set.
func (o *EmailDetectEvidence) HasDetectionLayer() bool {
	if o != nil && !IsNil(o.DetectionLayer) {
		return true
	}

	return false
}

// SetDetectionLayer gets a reference to the given string and assigns it to the DetectionLayer field.
func (o *EmailDetectEvidence) SetDetectionLayer(v string) {
	o.DetectionLayer = &v
}

// GetSourceCount returns the SourceCount field value if set, zero value otherwise.
func (o *EmailDetectEvidence) GetSourceCount() int32 {
	if o == nil || IsNil(o.SourceCount) {
		var ret int32
		return ret
	}
	return *o.SourceCount
}

// GetSourceCountOk returns a tuple with the SourceCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EmailDetectEvidence) GetSourceCountOk() (*int32, bool) {
	if o == nil || IsNil(o.SourceCount) {
		return nil, false
	}
	return o.SourceCount, true
}

// HasSourceCount returns a boolean if a field has been set.
func (o *EmailDetectEvidence) HasSourceCount() bool {
	if o != nil && !IsNil(o.SourceCount) {
		return true
	}

	return false
}

// SetSourceCount gets a reference to the given int32 and assigns it to the SourceCount field.
func (o *EmailDetectEvidence) SetSourceCount(v int32) {
	o.SourceCount = &v
}

func (o EmailDetectEvidence) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EmailDetectEvidence) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ClusterProvider) {
		toSerialize["cluster_provider"] = o.ClusterProvider
	}
	if !IsNil(o.DetectionLayer) {
		toSerialize["detection_layer"] = o.DetectionLayer
	}
	if !IsNil(o.SourceCount) {
		toSerialize["source_count"] = o.SourceCount
	}
	return toSerialize, nil
}

type NullableEmailDetectEvidence struct {
	value *EmailDetectEvidence
	isSet bool
}

func (v NullableEmailDetectEvidence) Get() *EmailDetectEvidence {
	return v.value
}

func (v *NullableEmailDetectEvidence) Set(val *EmailDetectEvidence) {
	v.value = val
	v.isSet = true
}

func (v NullableEmailDetectEvidence) IsSet() bool {
	return v.isSet
}

func (v *NullableEmailDetectEvidence) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEmailDetectEvidence(val *EmailDetectEvidence) *NullableEmailDetectEvidence {
	return &NullableEmailDetectEvidence{value: val, isSet: true}
}

func (v NullableEmailDetectEvidence) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEmailDetectEvidence) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


