/*
EmailGuard Public API

Team-scoped REST API at /api/v1. Authenticate with `Authorization: Bearer egsk_live_...` or `X-API-Key`. Forks may register custom routes under /api/v1/tools/_* (requires `tools:read` / `tools:write` scopes). Async tool jobs return a `job_id` — poll `GET .../{jobId}/results` until complete. See /docs/api-reference.

API version: 1.0
Contact: dev@emailguard.co
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package emailguardsdk

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the GetPublicTeamResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetPublicTeamResponse{}

// GetPublicTeamResponse struct for GetPublicTeamResponse
type GetPublicTeamResponse struct {
	// Machine-readable status code (for example OK or INVALID_BODY).
	Code string `json:"code"`
	Data *PublicTeamResponse `json:"data,omitempty"`
	// Human-readable detail when the code is not OK.
	Message *string `json:"message,omitempty"`
}

type _GetPublicTeamResponse GetPublicTeamResponse

// NewGetPublicTeamResponse instantiates a new GetPublicTeamResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetPublicTeamResponse(code string) *GetPublicTeamResponse {
	this := GetPublicTeamResponse{}
	this.Code = code
	return &this
}

// NewGetPublicTeamResponseWithDefaults instantiates a new GetPublicTeamResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetPublicTeamResponseWithDefaults() *GetPublicTeamResponse {
	this := GetPublicTeamResponse{}
	return &this
}

// GetCode returns the Code field value
func (o *GetPublicTeamResponse) GetCode() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Code
}

// GetCodeOk returns a tuple with the Code field value
// and a boolean to check if the value has been set.
func (o *GetPublicTeamResponse) GetCodeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Code, true
}

// SetCode sets field value
func (o *GetPublicTeamResponse) SetCode(v string) {
	o.Code = v
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *GetPublicTeamResponse) GetData() PublicTeamResponse {
	if o == nil || IsNil(o.Data) {
		var ret PublicTeamResponse
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetPublicTeamResponse) GetDataOk() (*PublicTeamResponse, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *GetPublicTeamResponse) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given PublicTeamResponse and assigns it to the Data field.
func (o *GetPublicTeamResponse) SetData(v PublicTeamResponse) {
	o.Data = &v
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *GetPublicTeamResponse) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetPublicTeamResponse) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *GetPublicTeamResponse) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *GetPublicTeamResponse) SetMessage(v string) {
	o.Message = &v
}

func (o GetPublicTeamResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetPublicTeamResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["code"] = o.Code
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	return toSerialize, nil
}

func (o *GetPublicTeamResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"code",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGetPublicTeamResponse := _GetPublicTeamResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGetPublicTeamResponse)

	if err != nil {
		return err
	}

	*o = GetPublicTeamResponse(varGetPublicTeamResponse)

	return err
}

type NullableGetPublicTeamResponse struct {
	value *GetPublicTeamResponse
	isSet bool
}

func (v NullableGetPublicTeamResponse) Get() *GetPublicTeamResponse {
	return v.value
}

func (v *NullableGetPublicTeamResponse) Set(val *GetPublicTeamResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableGetPublicTeamResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableGetPublicTeamResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetPublicTeamResponse(val *GetPublicTeamResponse) *NullableGetPublicTeamResponse {
	return &NullableGetPublicTeamResponse{value: val, isSet: true}
}

func (v NullableGetPublicTeamResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetPublicTeamResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


