// Code generated by scripts/clients/generate-go-facade.mjs; DO NOT EDIT.
package emailguardsdk

import (
	"context"

	"github.com/EmailGuard/emailguard-go/internal/openapi"
)

type RulesService struct {
	api *openapi.RulesAPIService
}

func newRulesService(transport *openapi.APIClient) *RulesService {
	return &RulesService{api: transport.RulesAPI}
}

func (s *RulesService) CreateNotificationRule(ctx context.Context, input CreateNotificationRuleInput) (*IdDataStruct, error) {
	request := s.api.CreateNotificationRule(ctx).CreateNotificationRuleInput(input)
	envelope, response, err := request.Execute()
	if err != nil {
		return nil, wrapHTTP(response, err)
	}
	if envelope == nil {
		return nil, newAPIError(0, "INVALID_RESPONSE", "API returned an empty response")
	}
	if err := checkEnvelope(envelope.Code, envelope.Message); err != nil {
		return nil, err
	}
	if envelope.Data == nil {
		return nil, newAPIError(0, "INVALID_RESPONSE", "API response did not include data")
	}
	return envelope.Data, nil
}

func (s *RulesService) DeleteNotificationRule(ctx context.Context, ruleId string) error {
	request := s.api.DeleteNotificationRule(ctx, ruleId)
	envelope, response, err := request.Execute()
	if err != nil {
		return wrapHTTP(response, err)
	}
	if envelope == nil {
		return newAPIError(0, "INVALID_RESPONSE", "API returned an empty response")
	}
	if err := checkEnvelope(envelope.Code, envelope.Message); err != nil {
		return err
	}
	return nil
}

func (s *RulesService) ListNotificationRules(ctx context.Context) ([]NotificationRuleResponse, error) {
	request := s.api.ListNotificationRules(ctx)
	envelope, response, err := request.Execute()
	if err != nil {
		return nil, wrapHTTP(response, err)
	}
	if envelope == nil {
		return nil, newAPIError(0, "INVALID_RESPONSE", "API returned an empty response")
	}
	if err := checkEnvelope(envelope.Code, envelope.Message); err != nil {
		return nil, err
	}
	return envelope.Data, nil
}

func (s *RulesService) UpdateNotificationRule(ctx context.Context, ruleId string, input UpdateNotificationRuleInput) error {
	request := s.api.UpdateNotificationRule(ctx, ruleId).UpdateNotificationRuleInput(input)
	envelope, response, err := request.Execute()
	if err != nil {
		return wrapHTTP(response, err)
	}
	if envelope == nil {
		return newAPIError(0, "INVALID_RESPONSE", "API returned an empty response")
	}
	if err := checkEnvelope(envelope.Code, envelope.Message); err != nil {
		return err
	}
	return nil
}
