// Code generated by scripts/clients/generate-go-facade.mjs; DO NOT EDIT.
package emailguardsdk

import (
	"context"

	"github.com/EmailGuard/emailguard-go/internal/openapi"
)

type TeamsService struct {
	api *openapi.TeamsAPIService
}

func newTeamsService(transport *openapi.APIClient) *TeamsService {
	return &TeamsService{api: transport.TeamsAPI}
}

func (s *TeamsService) GetTeam(ctx context.Context) (*PublicTeamResponse, error) {
	request := s.api.GetTeam(ctx)
	envelope, response, err := request.Execute()
	if err != nil {
		return nil, wrapHTTP(response, err)
	}
	if envelope == nil {
		return nil, newAPIError(0, "INVALID_RESPONSE", "API returned an empty response")
	}
	if err := checkEnvelope(envelope.Code, envelope.Message); err != nil {
		return nil, err
	}
	if envelope.Data == nil {
		return nil, newAPIError(0, "INVALID_RESPONSE", "API response did not include data")
	}
	return envelope.Data, nil
}

func (s *TeamsService) UpdateTeam(ctx context.Context, input UpdateTeamInput) (*PublicTeamResponse, error) {
	request := s.api.UpdateTeam(ctx).UpdateTeamInput(input)
	envelope, response, err := request.Execute()
	if err != nil {
		return nil, wrapHTTP(response, err)
	}
	if envelope == nil {
		return nil, newAPIError(0, "INVALID_RESPONSE", "API returned an empty response")
	}
	if err := checkEnvelope(envelope.Code, envelope.Message); err != nil {
		return nil, err
	}
	if envelope.Data == nil {
		return nil, newAPIError(0, "INVALID_RESPONSE", "API response did not include data")
	}
	return envelope.Data, nil
}
