/*
EmailGuard Public API

Team-scoped REST API at /api/v1. Authenticate with `Authorization: Bearer egsk_live_...` or `X-API-Key`. Forks may register custom routes under /api/v1/tools/_* (requires `tools:read` / `tools:write` scopes). Async tool jobs return a `job_id` — poll `GET .../{jobId}/results` until complete. See /docs/api-reference.

API version: 1.3
Contact: dev@emailguard.co
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the EmailDetectMatchedRule type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EmailDetectMatchedRule{}

// EmailDetectMatchedRule struct for EmailDetectMatchedRule
type EmailDetectMatchedRule struct {
	Id *string `json:"id,omitempty"`
	Label *string `json:"label,omitempty"`
	Signal *string `json:"signal,omitempty"`
}

// NewEmailDetectMatchedRule instantiates a new EmailDetectMatchedRule object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEmailDetectMatchedRule() *EmailDetectMatchedRule {
	this := EmailDetectMatchedRule{}
	return &this
}

// NewEmailDetectMatchedRuleWithDefaults instantiates a new EmailDetectMatchedRule object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEmailDetectMatchedRuleWithDefaults() *EmailDetectMatchedRule {
	this := EmailDetectMatchedRule{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *EmailDetectMatchedRule) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EmailDetectMatchedRule) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *EmailDetectMatchedRule) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *EmailDetectMatchedRule) SetId(v string) {
	o.Id = &v
}

// GetLabel returns the Label field value if set, zero value otherwise.
func (o *EmailDetectMatchedRule) GetLabel() string {
	if o == nil || IsNil(o.Label) {
		var ret string
		return ret
	}
	return *o.Label
}

// GetLabelOk returns a tuple with the Label field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EmailDetectMatchedRule) GetLabelOk() (*string, bool) {
	if o == nil || IsNil(o.Label) {
		return nil, false
	}
	return o.Label, true
}

// HasLabel returns a boolean if a field has been set.
func (o *EmailDetectMatchedRule) HasLabel() bool {
	if o != nil && !IsNil(o.Label) {
		return true
	}

	return false
}

// SetLabel gets a reference to the given string and assigns it to the Label field.
func (o *EmailDetectMatchedRule) SetLabel(v string) {
	o.Label = &v
}

// GetSignal returns the Signal field value if set, zero value otherwise.
func (o *EmailDetectMatchedRule) GetSignal() string {
	if o == nil || IsNil(o.Signal) {
		var ret string
		return ret
	}
	return *o.Signal
}

// GetSignalOk returns a tuple with the Signal field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EmailDetectMatchedRule) GetSignalOk() (*string, bool) {
	if o == nil || IsNil(o.Signal) {
		return nil, false
	}
	return o.Signal, true
}

// HasSignal returns a boolean if a field has been set.
func (o *EmailDetectMatchedRule) HasSignal() bool {
	if o != nil && !IsNil(o.Signal) {
		return true
	}

	return false
}

// SetSignal gets a reference to the given string and assigns it to the Signal field.
func (o *EmailDetectMatchedRule) SetSignal(v string) {
	o.Signal = &v
}

func (o EmailDetectMatchedRule) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EmailDetectMatchedRule) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Label) {
		toSerialize["label"] = o.Label
	}
	if !IsNil(o.Signal) {
		toSerialize["signal"] = o.Signal
	}
	return toSerialize, nil
}

type NullableEmailDetectMatchedRule struct {
	value *EmailDetectMatchedRule
	isSet bool
}

func (v NullableEmailDetectMatchedRule) Get() *EmailDetectMatchedRule {
	return v.value
}

func (v *NullableEmailDetectMatchedRule) Set(val *EmailDetectMatchedRule) {
	v.value = val
	v.isSet = true
}

func (v NullableEmailDetectMatchedRule) IsSet() bool {
	return v.isSet
}

func (v *NullableEmailDetectMatchedRule) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEmailDetectMatchedRule(val *EmailDetectMatchedRule) *NullableEmailDetectMatchedRule {
	return &NullableEmailDetectMatchedRule{value: val, isSet: true}
}

func (v NullableEmailDetectMatchedRule) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEmailDetectMatchedRule) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
