/*
EmailGuard Public API

Team-scoped REST API at /api/v1. Authenticate with `Authorization: Bearer egsk_live_...` or `X-API-Key`. Forks may register custom routes under /api/v1/tools/_* (requires `tools:read` / `tools:write` scopes). Async tool jobs return a `job_id` — poll `GET .../{jobId}/results` until complete. See /docs/api-reference.

API version: 1.3
Contact: dev@emailguard.co
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the PublicUpdateTeamMemberInput type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PublicUpdateTeamMemberInput{}

// PublicUpdateTeamMemberInput struct for PublicUpdateTeamMemberInput
type PublicUpdateTeamMemberInput struct {
	// Internal notes about the member. Omit to leave unchanged.
	Notes *string `json:"notes,omitempty"`
	// New team role (for example Owner, Admin, Member). Omit to leave unchanged. See [Team roles and permissions](/docs/knowledge-base/team-roles-and-permissions).
	Role *string `json:"role,omitempty"`
}

// NewPublicUpdateTeamMemberInput instantiates a new PublicUpdateTeamMemberInput object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPublicUpdateTeamMemberInput() *PublicUpdateTeamMemberInput {
	this := PublicUpdateTeamMemberInput{}
	return &this
}

// NewPublicUpdateTeamMemberInputWithDefaults instantiates a new PublicUpdateTeamMemberInput object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPublicUpdateTeamMemberInputWithDefaults() *PublicUpdateTeamMemberInput {
	this := PublicUpdateTeamMemberInput{}
	return &this
}

// GetNotes returns the Notes field value if set, zero value otherwise.
func (o *PublicUpdateTeamMemberInput) GetNotes() string {
	if o == nil || IsNil(o.Notes) {
		var ret string
		return ret
	}
	return *o.Notes
}

// GetNotesOk returns a tuple with the Notes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PublicUpdateTeamMemberInput) GetNotesOk() (*string, bool) {
	if o == nil || IsNil(o.Notes) {
		return nil, false
	}
	return o.Notes, true
}

// HasNotes returns a boolean if a field has been set.
func (o *PublicUpdateTeamMemberInput) HasNotes() bool {
	if o != nil && !IsNil(o.Notes) {
		return true
	}

	return false
}

// SetNotes gets a reference to the given string and assigns it to the Notes field.
func (o *PublicUpdateTeamMemberInput) SetNotes(v string) {
	o.Notes = &v
}

// GetRole returns the Role field value if set, zero value otherwise.
func (o *PublicUpdateTeamMemberInput) GetRole() string {
	if o == nil || IsNil(o.Role) {
		var ret string
		return ret
	}
	return *o.Role
}

// GetRoleOk returns a tuple with the Role field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *PublicUpdateTeamMemberInput) GetRoleOk() (*string, bool) {
	if o == nil || IsNil(o.Role) {
		return nil, false
	}
	return o.Role, true
}

// HasRole returns a boolean if a field has been set.
func (o *PublicUpdateTeamMemberInput) HasRole() bool {
	if o != nil && !IsNil(o.Role) {
		return true
	}

	return false
}

// SetRole gets a reference to the given string and assigns it to the Role field.
func (o *PublicUpdateTeamMemberInput) SetRole(v string) {
	o.Role = &v
}

func (o PublicUpdateTeamMemberInput) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PublicUpdateTeamMemberInput) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Notes) {
		toSerialize["notes"] = o.Notes
	}
	if !IsNil(o.Role) {
		toSerialize["role"] = o.Role
	}
	return toSerialize, nil
}

type NullablePublicUpdateTeamMemberInput struct {
	value *PublicUpdateTeamMemberInput
	isSet bool
}

func (v NullablePublicUpdateTeamMemberInput) Get() *PublicUpdateTeamMemberInput {
	return v.value
}

func (v *NullablePublicUpdateTeamMemberInput) Set(val *PublicUpdateTeamMemberInput) {
	v.value = val
	v.isSet = true
}

func (v NullablePublicUpdateTeamMemberInput) IsSet() bool {
	return v.isSet
}

func (v *NullablePublicUpdateTeamMemberInput) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePublicUpdateTeamMemberInput(val *PublicUpdateTeamMemberInput) *NullablePublicUpdateTeamMemberInput {
	return &NullablePublicUpdateTeamMemberInput{value: val, isSet: true}
}

func (v NullablePublicUpdateTeamMemberInput) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePublicUpdateTeamMemberInput) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
